### ISSUE TITLE
numpy.linalg.linalg.LinAlgError on a bbob-biobj problem

### ISSUE THREAD

**Issue by brockho** [CMA-ES/pycma#10]
I ran a relatively long experiment on the [biobjective BBOB](http://numbbo.github.io/coco-doc/bbob-biobj/functions/) test suite of [COCO](https://github.com/numbbo/coco) in which CMA-ES optimizes a quite simple weighted sum of the two objective functions (optimizing 50 weighted sums per problem in a total budget of 1e5 times dimension including restarts and using the default options of CMA-ES). One of the experiment's 10 batches crashed in 40-D with the following error message:
```
bbob-biobj_f47_i02_d40 2-objective problem (bbob-biobj(bbob_f015_i03_d40__bbob_f017_i05_d40)(7591))
  --> new weight: 7.346939e-01
bbob-biobj_f47_i02_d40 2-objective problem (bbob-biobj(bbob_f015_i03_d40__bbob_f017_i05_d40)(7591))
  --> new weight: 7.142857e-01
bbob-biobj_f47_i02_d40 2-objective problem (bbob-biobj(bbob_f015_i03_d40__bbob_f017_i05_d40)(7591))
  --> new weight: 6.938776e-01
Traceback (most recent call last):
  File "example_experiment-WS-normalized.py", line 488, in <module>
    main(budget, max_runs, current_batch, number_of_batches)
  File "example_experiment-WS-normalized.py", line 465, in main
    current_batch, number_of_batches)
  File "example_experiment-WS-normalized.py", line 334, in batch_loop
    max_runs)
  File "example_experiment-WS-normalized.py", line 396, in coco_optimize
    solver(fun, budget)
  File "example_experiment-WS-normalized.py", line 263, in weighted_sum_search
    ideal=ideal, nadir=nadir)
  File "example_experiment-WS-normalized.py", line 292, in runCMAESWithWeightedSum
    solutions = es.ask()
  File "/home2/users/dimo.brockhoff/WS-77/cma/evolution_strategy.py", line 1674, in ask
    pop_geno = self.ask_geno(number, xmean, sigma_fac)
  File "/home2/users/dimo.brockhoff/WS-77/cma/evolution_strategy.py", line 1918, in ask_geno
    ary = self.sigma_vec * self.sm.sample(Niid)
  File "/home2/users/dimo.brockhoff/WS-77/cma/sampler.py", line 222, in sample
    self.update_now(lazy_update_gap)
  File "/home2/users/dimo.brockhoff/WS-77/cma/sampler.py", line 293, in update_now
    self._decompose_C()
  File "/home2/users/dimo.brockhoff/WS-77/cma/sampler.py", line 339, in _decompose_C
    self.D, self.B = self.eigenmethod(self.C)
  File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 1187, in eigh
    raise LinAlgError, 'Eigenvalues did not converge'
numpy.linalg.linalg.LinAlgError: Eigenvalues did not converge
```
Unfortunately, I turned off the output of CMA-ES to not produce too large output files. I could try to find a random seed that will reproduce the error by running the experiment again just on this function.

**Comment by brockho** [comment]
I now rerun the experiment which showed a crash on another problem instance. Most importantly, I could record the random seed for reproducing the error (the error message is the same as above and thus cut):
```
bbob-biobj_f48_i04_d40 2-objective problem (bbob-biobj(bbob_f015_i09_d40__bbob_f020_i10_d40)(7608))
  --> new weight: 1.020408e-01
(7_w,15)-aCMA-ES (mu_w=4.5,w_1=34%) in dimension 40 (seed=361690, Sat May 20 02:19:30 2017)
(7_w,15)-aCMA-ES (mu_w=4.5,w_1=34%) in dimension 40 (seed=402495, Sat May 20 02:19:35 2017)
Traceback (most recent call last):
  File "example_experiment-WS-normalized.py", line 488, in <module>
    main(budget, max_runs, current_batch, number_of_batches)
[...]
  File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 1187, in eigh
    raise LinAlgError, 'Eigenvalues did not converge'
numpy.linalg.linalg.LinAlgError: Eigenvalues did not converge
```

**Comment by nikohansen** [comment]
Excellent, now to reproduce the error it would be useful to also have the objective function definition and the precise arguments with which `cma.fmin` was called.

**Comment by brockho** [comment]
After quite some trials to find again the right random seed that reproduces the error (I had to run about 50 runs with different random seeds to find one that actually gives an error). The attached zip file below gives the corresponding example experiment that failed.

[example_experiment-WS-normalized-reconstructerror.zip](https://github.com/CMA-ES/pycma/files/1106738/example_experiment-WS-normalized-reconstructerror.zip)

Note that I realized later on that the error is not reproducible on all our compute servers! Here are some details on the machines where it worked and where it failed:

working on porte-d-auteuil with
python 2.7.3, numpy 1.6.1, GCC 4.6.3 (linux 2)

not working on porte-de-la-chapelle with
python 2.6.6, numpy 1.10.4, GCC 4.4.7 20120313 (Red Hat 4.4.7-3)

In both cases, I use the same CMA-ES version, imported from a zip file, obtained from the `pycma` github page:
```
>>> import cma
>>> cma.__version__
'2.1.0  $Revision: 4394 $ $Date: 2017-05-13 15:04:41 +0200 (Sat, 13 May 2017) $'
```

Hope this helps. @nikohansen: if you need more details about the machines, please let me know. I can also tell you offline where the code is located to actually reproduce the error yourself.

**Comment by nikohansen** [comment]
@brockho I unzipped the above file, but I am not sure whether I tested the right thing, I namely called the script with the parameter `bbob-biobj 1e5`, which doesn't reproduce the error.

**Comment by nikohansen** [comment]
The [above referenced commit](de30cca) should convert the error into a warning. I am undecided though whether this is a good or a bad thing, as this may obscure the observation that something weird is going on.

**Comment by brockho** [comment]
Did you try on your machine or on `porte-de-la-chapelle` in the lab? On `porte-d-auteuil`, for example, I could also not reproduce the error.
