### ISSUE TITLE
change plot layout

### ISSUE THREAD

**Issue by ggrrll** [CMA-ES/pycma#101]
Hi, 

thanks for the package.
I was wondering if there is a way to set the [`figsize`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.figure.html) in logger plot, such as `cma.plot()` -- otherwise I think would be nice to expose such parameter, as sometimes the subplots get messed up and the axis are unreadable (or something like `plt.tight_layout()`) 

Thanks

**Comment by nikohansen** [comment]
I think figure parameters are exposed by using `matplotlib`: `fig = plt.gcf()` gives the handle to the current figure which should allow any such change? Assigning `plt.rcParams["figure.figsize"]` to the desired value before invoking the plot does the job too.
