### ISSUE TITLE
4x performance improvement with numpy data for diagonal CMA

### ISSUE THREAD

**Issue by ARF1** [CMA-ES/pycma#106]
I am optimizing a function that evaluates fast compared to pycma. Thus my performance was limited by pycma.

Profiling the code I found that an exceeding amount of CPU time was spend in the function `utilities.utils.SolutionDict.__getitem__()`

The following fast-path for numpy data leads to a better than 4x performance improvement for my problem:

```
import cma.utilities.utils
class PseudoDict:
    def key(self, x):
        """compute key of ``x``"""
        # numpy fast path
        if type(x) is np.ndarray:
            return hash(x.data.tobytes())
        # fall-back to default path
        try:
            return tuple(x)
            # using sum(x) is slower, using x[0] is slightly faster
        except TypeError:
            return x
cma.utilities.utils.SolutionDict.key = PseudoDict.key
```

Same idea, same performance for numpy input (but due to the use of exceptions may be slower for non-numpy input than the first solution. Not separately profiled as the first solution is my prefered solution.):
```
import cma.utilities.utils
class PseudoDict:
    def key(self, x):
        """compute key of ``x``"""
        try:
            # numpy fast path
            return hash(x.data.tobytes())
        except AttributeError:
            # fall-back to default path
            try:
                return tuple(x)
                # using sum(x) is slower, using x[0] is slightly faster
            except TypeError:
                return x
cma.utilities.utils.SolutionDict.key = PseudoDict.key
```

In the above examples, the fix was implemented using monkey-patching. Let me know if I should submit a PR which adds these two line directly to `utilities.utils.SolutionDict.key()`

-----
**Edit 1: Profiling data**

Status quo:

![image](https://user-images.githubusercontent.com/5834577/70372665-5a9aee80-18e2-11ea-9049-abbdb69f6f5e.png)

After monkey-patching:

![image](https://user-images.githubusercontent.com/5834577/70372669-64bced00-18e2-11ea-9067-0248e8699cf7.png)

`train_nn` is my objective function. It goes from 7.8% to 33% of the CPU time spent in the optimization section of the code.

**Comment by nikohansen** [comment]
Thanks for the observations! I'd prefer the try-except route. I also wonder why it is advantageous to use the `hash` function at all. The key could just be `x.data.tobytes()` which seems, depending on the dimension, to be considerably faster to execute than `hash(x.data.tobytes())`.

**Comment by ARF1** [comment]
@nikohansen I used the content hash for numpy because the original code also used conten hashing. I did not study the code thoroughly and did not want to introduce unwanted side-effects.

The original code was:
```
    def key(self, x):
        """compute key of ``x``"""
        try:
            return tuple(x)
            # using sum(x) is slower, using x[0] is slightly faster
        except TypeError:
            return x
    def __getitem__(self, key):  # 50% of time of
        """define access ``self[key]``"""
        return self.data[self.key(key)]
```

Here `tuple(x)` has the effect of hashing on the contents of `x`. Hence, I used content hashing for numpy inputs as well. If this is not required for the proper functioning of the code, using the identity of `x` as key would definitely be preferable.

**Comment by ARF1** [comment]
@nikohansen On second thought, hashing is not required because the dict will hash the sequence of bytes used as key anyway. 

Not hashing might however double memory usage: The dict does store all byte sequences used as keys in addition to their hashes. Otherwise it would not be possible to get a list of keys used from a dict with `.keys()`. - I cannot say if the additional memory usage is likely to be an issue.

**Comment by nikohansen** [comment]
FTR, `tuple(x)` is needed to create an immutable, hence hashable, `type` from `x` which can be used as a key. `hash(tuple(x))` would also work but `hash(x)` does not.

**Comment by nikohansen** [comment]
Fixing [the Python 2 problem](https://ci.appveyor.com/project/nikohansen/pycma/builds/29989174/job/40rhjn4a1ff36t0a) and introducing the possibility to patch the hash function on the fly:
```python
    @staticmethod
    def _hash(x):
        return x
    def key(self, x):
        """compute key of ``x``"""
        try:
            return self._hash(np.ascontiguousarray(x).data.tobytes())  # much faster than tuple(.)
        except AttributeError:
            try:
                return self._hash(tuple(x))  # using sum(x) is slower, using x[0] is slightly faster
            except TypeError:
                return self._hash(x)

```

**Comment by ARF1** [comment]
@nikohansen I was not sure whether you wanted me to do anything here but I amended #107 with your code.

**Comment by nikohansen** [comment]
Did you click on the above Python 3 problem link?

**Comment by ARF1** [comment]
@nikohansen Sorry, I overlooked this. Thanks.
