### ISSUE TITLE
"maxfevals" option not working 

### ISSUE THREAD

**Issue by a-z-e-r-i-l-a** [CMA-ES/pycma#108]
Hi, I am using the pycma and do not want the optimizer to evaluate the objective more than 5 times for example, for which I use the maxfevals option  like the following:

```
res = cma.fmin(func,
                   x0=10*[0],
                   sigma0=0.5,
                   options={"bounds":    bounds.T.tolist(),
                            'maxfevals': 5,
                            'CMA_stds' : np.abs(bounds).min(1).tolist(),
                            "verbose": 1})
```

However cma.fmin still evaluates the 'func' objective more than 5 times.

**Comment by nikohansen** [comment]
The algorithm is iteration-based and will always complete the iteration before to check the termination condition.

If the user desires to control this more precisely, they can use the more verbose interface which gives full control over each function call as described [here](http://cma.gforge.inria.fr/apidocs-pycma/cma.evolution_strategy.CMAEvolutionStrategy.html).

**Comment by a-z-e-r-i-l-a** [comment]
does it make sense to set popsize to a fixed number of evaluations that we want?
