### ISSUE TITLE
es.ask() memory increase

### ISSUE THREAD

**Issue by Evi5** [CMA-ES/pycma#109]
import cma

if __name__ == '__main__':
    num_params = 1000
    sigma_init = 0.10
    popsize = 4
    es = cma.CMAEvolutionStrategy( num_params * [0], sigma_init, {'popsize': popsize,})
    while True:
        solutions = es.ask()
        #es.tell(solutions, [cma.ff.rosen(x) for x in solutions])
        #es.disp()

-----------------------------------------------------------------------------------------
The above code will slowly increase memory， is that right or memory leak?

in my code of project
solutions = es.ask()

> get reward_list

es.tell(solutions, reward_list)

> get es.result

but memory increase until memory full and find that es.tell make memory increase.

**Comment by nikohansen** [comment]
The memory is expected to increase only in the first hundred-or-so iterations. Otherwise I would consider it to be a bug.
