### ISSUE TITLE
Setup.py does not specify utilities subpackage

### ISSUE THREAD

**Issue by admcrae** [CMA-ES/pycma#11]
With my python configuration (python 3.5 on Ubuntu 16.04), the `cma.utilities` subpackage does not get installed when I install the cma package from source. My guess is that the `packages` argument of `setup` should include `cma.utilities`.

EDIT: I can confirm that adding `cma.utilities` to the `packages` argument resolves this problem.

**Comment by nikohansen** [comment]
Thanks for the report and proposed fix! Does that mean you got an error during the installation or when importing the module `cma`?

**Comment by admcrae** [comment]
When importing the module `cma`. Running `pip install <source folder>` did not add the `utilities` folder to the appropriate directory in `site-packages`, which obviously made trying to import anything that depended on it throw an error.

**Comment by admcrae** [comment]
Another potential fix would be to make the argument `packages=find_packages()`.

**Comment by nikohansen** [comment]
Fixed (though I wasn't able to reproduce the problem myself, so I can't exactly test the fix).
