### ISSUE TITLE
Constrained Weight Optimization

### ISSUE THREAD

**Issue by kennybix** [CMA-ES/pycma#110]
Please  how do I add constraint function such as "constraint_func"?

```
def constraint_func(weights):
      return sum(weights) - 1

```

**Comment by nikohansen** [comment]
Constraints handling will become soon available in the module, but is currently not. The above constraints function is probably better treated by normalizing the weights like `weights = weights / sum(weights)` when used in the objective and adding a mild penalty like `1e-6 * constraint_func(weights)**2` to the objective function value. That is, for example, using an instance of
```python
import numpy as np
class WrapObjective:
    def __init__(self, objective, penalty_coefficient=1e-6):
        self.objective = objective
        self.penalty_coefficient = penalty_coefficient
    def __call__(self, weights):
        weights = np.asarray(weights)
        s = np.sum(weights)
        return self.objective(weights / s) + self.penalty_coefficient * (s - 1)**2
```
as objective function. If the weights should also stay positive, the following looks (more) promising:
```python
    def __call__(self, weights):
        weights = np.asarray(weights)**2  # mapping of weights variables to positive domain
        s = np.sum(weights)
        return self.objective(weights / s) + self.penalty_coefficient * (s - 1)**2
```

**Comment by pedrocTC** [comment]
Has this functionality been implemented?
