### ISSUE TITLE
Seed 0 is over-ridden

### ISSUE THREAD

**Issue by jmmcd** [CMA-ES/pycma#111]
Setting seed = 0 causes cma to set its own seed:
```
>>> es = cma.CMAEvolutionStrategy(4 * [1], 1, {'seed': 0, 'bounds': [[0, 0, 0, 0], [10, 10, 10, 10]]})
(4_w,8)-aCMA-ES (mu_w=2.6,w_1=52%) in dimension 4 (seed=248379, Wed Jan 15 23:16:10 2020)
```

But any other seed is respected:
```
>>> es = cma.CMAEvolutionStrategy(4 * [1], 1, {'seed':1, 'bounds': [[0, 0, 0, 0], [10, 10, 10, 10]]})
(4_w,8)-aCMA-ES (mu_w=2.6,w_1=52%) in dimension 4 (seed=1, Wed Jan 15 23:17:21 2020)
```

**Comment by jmmcd** [comment]
I guess that [this line](https://github.com/CMA-ES/pycma/blob/814cd22271621608e61618d5d6080e21aa5712bd/cma/evolution_strategy.py#L1379) is finding that `not 0` is `True`, giving this behaviour: 

```
               if not opts['seed'] or opts['seed'] is time:
```

But I see [here](https://github.com/CMA-ES/pycma/blob/814cd22271621608e61618d5d6080e21aa5712bd/cma/evolution_strategy.py#L460) that this behaviour is expected.

**Comment by nikohansen** [comment]
Correct, it may not be the ideal interface, but for the time being I am also not inclined to change it and break backwards compatibility.
```python
import cma
print(cma.CMAOptions('seed'))
```
```
{'seed': 'time  # random number seed for `numpy.random`; `None` and `0` equate to `time`, `np.nan` means "do nothing", see also option "randn"'}
```
