### ISSUE TITLE
Multi-objective optimization?

### ISSUE THREAD

**Issue by jvita** [CMA-ES/pycma#119]
Hello,

First of all, let me say thank you for 1) developing this outstanding algorithm, and 2) building an efficient, open-source implementation. I use your code in my work, and it performs beautifully.

I recently started becoming interested in Pareto front sampling (rather than just single-objective optimization), and noticed that you already had [a paper discussing this](https://www.ncbi.nlm.nih.gov/pubmed/17388777).

Is MO-CMA-ES already implemented in this package? If not, do you have any suggestions about where I might look to start making the necessary modifications myself (either by modifying the pycma source code or by writing a wrapper)?

Thanks,
Josh

**Comment by nikohansen** [comment]
I am not aware of a Python implementation of MO-CMA-ES and it would also be not so clear to me how to implement it based on the `pycma` module. There is an implementation of [COMO-CMA-ES](https://dl.acm.org/doi/pdf/10.1145/3321707.3321852) based on `pycma`, but I don't think it is public yet (though it should be at some point).

**Comment by jvita** [comment]
I hadn't encountered that paper yet, but I like it's ideas. While I see how the algorithm shouldn't be too difficult to implement since `pycma` is already available for handling all of the single-objective optimizers, it would be nice to not have to re-implement it if there's already an existing package.

I would be extremely interested in working with Sofomore, even just to serve as a beta-tester. Would I need to contact the first author of the paper that you mentioned, or do you know who else I might need to get in touch with?

**Comment by cheikhToure** [comment]
Hello @jvita,
The code for [COMO-CMA-ES](https://dl.acm.org/doi/pdf/10.1145/3321707.3321852) is now released and available at https://github.com/CMA-ES/pycomocma.

**Comment by jvita** [comment]
Fantastic, thanks for letting me know! I'm looking forward to checking it out.
