### ISSUE TITLE
Countevals is only incremented by the number of evaluations on feasible solutions

### ISSUE THREAD

**Issue by krtab** [CMA-ES/pycma#121]
Hi !

Thanks for all the work on this package!

I believe that there is an issue (or an imprecision in the documentation) concerning the `maxfevals` stop criterion when doing rejection sampling using `ask_and_eval`. Indeed, `countevals` is only incremented in `tell`, which can only see the *popsize* samples that have not been rejected. Hence, `countevals` is equals to the number of iterations times *popsize*, which in my opinion isn't its expected behavior. 

For example, using CMA-ES to fit an ODE model to data, many parameters values will fail to be integrated. While I have a maxfevals stop criterion, different runs of the fitting script lead to varying running times, depending on whether the search has encountered a lot of unfeasible points, while I would expect all runs to be about the same duration on the same hardware.

Let me know if I can help you!

**Comment by nikohansen** [comment]
I assume adding the `rejected` count to `self.countevals` [at the end of the for-loop of `ask_and_eval`](https://github.com/CMA-ES/pycma/blob/master/cma/evolution_strategy.py#L2333) would fix the problem. There could be cases though where rejection is cheap and we do not want to count these?

**Comment by nikohansen** [comment]
There is [a timeout option](https://github.com/CMA-ES/pycma/blob/dfed2bdd2bd5334bfd407d6cdbefbe0f8638f795/cma/evolution_strategy.py#L464) that should fit the demand for same duration of runs.
