### ISSUE TITLE
Explanation on how to change the internal parameters within the CMA

### ISSUE THREAD

**Issue by JosephStantonIT** [CMA-ES/pycma#122]
I have been searching through the tutorial provided and have changed the population size a couple of times as well as sigma however I would like to see the effects of changing the internal parameters within the CMA algorithm. How could I do this?

Thanks in advance.

**Comment by nikohansen** [comment]
I am not sure I understand the question. If I want to see the effects of parameter changes I look at the graphs produced by `cma.plot()`.

**Comment by JosephStantonIT** [comment]
Currently I am using the CMA algorithm to carry out hyper-parameter tuning of a model (with 13 continuous hyper-parameters with a boundary between [0,1]). I have been using CMA on its default settings (only changing the population size to see if I could obtain a better score from the objective function). Is it possible to change and "tune" the internal parameters of the CMA algorithm to fit my particular model?

I would like to run the algorithm changing the learning rates, ranking order for solutions etc.

**Comment by nikohansen** [comment]
A pointer to start with: [Loshchilov et al 2014](https://scholar.google.fr/scholar?cluster=5438345182472074787). The code in this repository also has annotations and collects possible internal parameters in the class [`cma.evolution_strategy.MetaParameters`](https://github.com/CMA-ES/pycma/blob/master/cma/evolution_strategy.py#L222). It's by no means a simple task though, I would say. The standard, most simple "solution" tunes only the population size by [restarts with increasing population size](https://scholar.google.fr/scholar?cluster=6757233182925514082) and there are also a few papers trying to adapt the population size ([2016](https://scholar.google.fr/scholar?cluster=16814522901498447512), [2018](https://scholar.google.fr/scholar?cluster=11525273129964725162)).
