### ISSUE TITLE
How to use EvalParallel2?

### ISSUE THREAD

**Issue by nju-luke** [CMA-ES/pycma#125]
I'm trying to use EvalParallel2 to speed up the training, but didn't get any improvements.
The toy code is as follows,
```python
import numpy as np
import cma

multip = 20
size = 8 * 20
w = np.array([1,2,3,4,5,4,3,2]*multip)

def get_fitness(x):
    return np.sum((x-w)**2)

opts = {'popsize' : 256,
        'ftarget': 1e-6
        }
es = cma.CMAEvolutionStrategy([0] *size , 1, opts)

if __name__ == '__main__':
    import time
    time1 = time.time()
    # es.optimize(get_fitness)

    with cma.fitness_transformations.EvalParallel2(get_fitness, 8) as eval_para:
        while not es.stop():
            X = es.ask()
            es.tell(X, eval_para(X))

    time2 = time.time()
    print(time2 - time1)
```

**Comment by nikohansen** [comment]
It would be helpful to see the timing results as well. Given how quickly `get_fitness` can be evaluated, AFAICS, I would be surprised to see any speed up.

Add
```python
time.sleep(0.1)
```
to the function and you should see the effect, [see also here](https://github.com/CMA-ES/pycma/issues/31#issuecomment-328143131).

**Comment by nju-luke** [comment]
> It would be helpful to see the timing results as well. Given how quickly `get_fitness` can be evaluated, AFAICS, I would be surprised to see any speed up.
> 
> Add
> 
> ```python
> time.sleep(0.1)
> ```
> 
> to the function and you should see the effect, [see also here](https://github.com/CMA-ES/pycma/issues/31#issuecomment-328143131).

@nikohansen Thank you for your reply.

It seems like the multiprocessing method is used to calculate the fitness
```python
# cma.fitness_transformations.EvalParallel2， line 188
        jobs = [self.pool.apply_async(fitness_function, (x,) + args)
                for x in solutions]
```
At the same time, additional  instances of ES are created? Do the offer any help for the fitting? 
```sh
(128_w,256)-aCMA-ES (mu_w=66.9,w_1=3%) in dimension 40 (seed=196461, Fri Apr 17 14:32:46 2020)
(128_w,256)-aCMA-ES (mu_w=66.9,w_1=3%) in dimension 40 (seed=251763, Fri Apr 17 14:32:52 2020)
(128_w,256)-aCMA-ES (mu_w=66.9,w_1=3%) in dimension 40 (seed=163160, Fri Apr 17 14:32:56 2020)
(128_w,256)-aCMA-ES (mu_w=66.9,w_1=3%) in dimension 40 (seed=217589, Fri Apr 17 14:32:59 2020)
(128_w,256)-aCMA-ES (mu_w=66.9,w_1=3%) in dimension 40 (seed=260288, Fri Apr 17 14:33:04 2020)
(128_w,256)-aCMA-ES (mu_w=66.9,w_1=3%) in dimension 40 (seed=251551, Fri Apr 17 14:33:07 2020)
(128_w,256)-aCMA-ES (mu_w=66.9,w_1=3%) in dimension 40 (seed=223245, Fri Apr 17 14:33:11 2020)
(128_w,256)-aCMA-ES (mu_w=66.9,w_1=3%) in dimension 40 (seed=226641, Fri Apr 17 14:33:15 2020)
(128_w,256)-aCMA-ES (mu_w=66.9,w_1=3%) in dimension 40 (seed=128852, Fri Apr 17 14:33:19 2020)
```

**Comment by nikohansen** [comment]
I can't understand how the above script can show the below output.

I get as output:

```
(128_w,256)-aCMA-ES (mu_w=66.9,w_1=3%) in dimension 160 (seed=216301, Fri Apr 17 10:47:14 2020)
41.25515079498291
```

When I run it without `EvalParallel2` it runs in about the same time (somewhat below 40s). When I add `time.sleep(0.01)` to `get_fitness` (or some other additional computations), the parallel version becomes more than five times faster than the one without `EvalParallel2` (I only tried with 15 iterations, `'maxiter': 15`).

This fits to the original conjecture that `get_fitness` is too quick to evaluate to see any advantage from scheduling the parallel pool.

> At the same time, additional instances of ES are created?

That should not be the case and seems not to be the case when I run the code.

> Do the offer any help for the fitting?

I don't understand the question.

**Comment by nikohansen** [comment]
OK, maybe I understand now: maybe the misunderstanding is the idea that the instance 
```python 
cma.fitness_transformations.EvalParallel2(get_fitness, 8)
```
parallelizes the function `get_fitness` (like into 8 chunks) which is not the case.

What it does is it to parallelize several independent calls to `get_fitness`.

FTR
```python
import numpy as np
import time
import cma

multip = 20
size = 8 * 20
w = np.array([1,2,3,4,5,4,3,2]*multip)

def get_fitness(x):
    for i in range(1000):
        y = randn(345)
    return np.sum((x-w)**2)

opts = {'popsize' : 256,
        'ftarget': 1e-6,
        'verbose': -1,
        'maxiter': 5
        }

n_proc = 0
for n_proc in range(1, 13):
    es = cma.CMAEvolutionStrategy([0] * size , 1, opts)
    time1 = time.time()
    with cma.fitness_transformations.EvalParallel2(get_fitness, n_proc) as eval_para:
        while not es.stop():
            X = es.ask()
            es.tell(X, eval_para(X))
    time2 = time.time()
    print(n_proc, time2 - time1)
```
produces this output:
```
0 10.272979974746704
1 10.6006441116333
2 5.68294095993042
3 4.040978908538818
4 3.107923984527588
5 2.6113929748535156
6 2.2902491092681885
7 2.086170196533203
8 1.9825901985168457
9 2.0872061252593994
10 1.9808261394500732
11 1.985576868057251
12 1.9830749034881592
```
that is, is five times faster when 8 processors are used.

**Comment by nju-luke** [comment]
If I use the code like this,
```python
    es = cma.CMAEvolutionStrategy([0] * size, 1, opts)
    with cma.fitness_transformations.EvalParallel2(get_fitness, 8) as eval_para:
        while not es.stop():
            X = es.ask()
            es.tell(X, eval_para(X))
```
additional instances of ES are created.

> ```shell
> (128_w,256)-aCMA-ES (mu_w=66.9,w_1=3%) in dimension 40 (seed=196461, Fri Apr 17 14:32:46 2020)
> (128_w,256)-aCMA-ES (mu_w=66.9,w_1=3%) in dimension 40 (seed=251763, Fri Apr 17 14:32:52 2020)
> (128_w,256)-aCMA-ES (mu_w=66.9,w_1=3%) in dimension 40 (seed=163160, Fri Apr 17 14:32:56 2020)
> ......
> ```

I find that this output is generated by the instantiation of the CMAEvolutionStrategy before EvalParallel2.  The multiprocessing operation will run all the code before itself. After I change it to the following, the output performs well. 
```python
    with cma.fitness_transformations.EvalParallel2(get_fitness, 8) as eval_para:
        es = cma.CMAEvolutionStrategy([0] * size, 1, opts)
        while not es.stop():
            X = es.ask()
            es.tell(X, eval_para(X))
```

Thank you for your reply.

**Comment by nikohansen** [comment]
I have no idea why this can even happen and I don't think it should. The first version looks correct and even more logical to me. Scratching head...

**Comment by nju-luke** [comment]
I can't reproduce the error described above, Scratching head...
But I find that the main reason for the additional instances may result from that I didn't put this line `es = cma.CMAEvolutionStrategy([0] *size , 1, opts)` in the main module. 
The multiprocessing operation will create `n` new processes by initializing all the objects before `if __name__ == '__main__':`. I made a mistake yesterday,
> The multiprocessing operation will run all the code before itself.
I'm so sorry for the trouble.
