### ISSUE TITLE
How to obtain the list of m and C at each iteration?

### ISSUE THREAD

**Issue by louiscam** [CMA-ES/pycma#129]
Hi,
I am currently running CMA-ES to minimize a fitness function f with domain \mathbb{R}^5, and would like to obtain, for each iteration, the corresponding values of the mean vector m and the covariance matrix C. Could you please let me know how to proceed? Thank you for your help!
Best,
Louis

**Comment by nikohansen** [comment]
One way to go about this is
```python
es = cma.CMAEvolutionStrategy(2 * [1], 1)
while not es.stop():
    es.optimize(cma.ff.elli, iterations=1)
    es.mean  # mean
    es.sigma  # std multiplier
    es.sigma_vec.scaling  # std multipliers in coordinate axis (usually one)
    es.sm.C  # covariance matrix without es.sigma and es
```
and check out ``help(es)`` for using the ask-and-tell interface. On the other hand, ``es.logger.plot()`` provides visualization of the covariance matrix, which is usually much more useful than staring at numbers.

**Comment by louiscam** [comment]
Thank you Niko this is very helpful! I wish you a great day.
Best,
Louis

**Comment by Cascol-Chen** [comment]
Hi, I tried to access ```es.sm.C``` under ```cma==3.3.0``` but came across an error ```AttributeError: 'GaussStandardConstant' object has no attribute 'C'```. 

Any kind help would be appreciated :)

**Comment by nikohansen** [comment]
This is bound to happen if you use the option ```{'CMA_on': 0}```. It would be very helpful if you show the calling code from which the error arises.

**Comment by Cascol-Chen** [comment]
Hi,

I am using the following configuration
```
cma_opts = {
    'seed': 2020,
    'popsize': popsize,
    'maxiter': -1,
    'verbose': -1,
    'CMA_diagonal': 1000000,
    'CMA_diagonal_decoding': True,
}
```

**Comment by nikohansen** [comment]
The covariance matrix is diagonal for the first 1000000 iterations, hence $`C`$ is the identity here. This is a strange setting when the search domain is $`\mathbb{R}^5`$. The above behavior is not ideal but expected. The `es.stds` represent the square roots of the diagonal elements of the covariance matrix $`D\times C \times D`$. The diagonal of the $`D`$ diagonal matrix is originally stored in the `scaling` attribute of the `sigma_vec` `DiagonalDecoding` class. `es.sm.C` is the identity but not stored, hence the error.

If  you want to scrutinize interesting state variables, including the mean, I'd also recommend to consider `cma.plot(plot_mean=True)` while the `verbose` option must be large enough such that the code writes data for plotting, see for example [here](https://github.com/CMA-ES/pycma/blob/development/notebooks/notebook-usecases-basics.ipynb). `'verb_disp_overwrite': 300` prevents flooding the screen in long runs.

**Comment by Cascol-Chen** [comment]
Thanks, that really helps~
