### ISSUE TITLE
Cannot save the figure

### ISSUE THREAD

**Issue by kontrabas380** [CMA-ES/pycma#131]
Hello,

I've got `Python 3.6.9` and:

`cma==3.0.3`
`matplotlib==3.2.1`

I've found problem when I tried to follow provided examples - I can't save the figure as in the documentation:
[https://github.com/CMA-ES/pycma/blob/master/cma/evolution_strategy.py#L4184](https://github.com/CMA-ES/pycma/blob/master/cma/evolution_strategy.py#L4184)

And later I've found that there:
[https://github.com/CMA-ES/pycma/blob/master/cma/s.py#L28](https://github.com/CMA-ES/pycma/blob/master/cma/s.py#L28)

is some courius condition which is why (probably) I'm getting error like this:
`module 'cma.s' has no attribute 'figsave'`

Am I doing something wrong or there is an issue with that?

Best regards.

**Comment by nikohansen** [comment]
Indeed, documentation and code do disagree here. This:

```python
import matplotlib.pyplot
cma.s.figsave = matplotlib.pyplot.savefig
```
would fix the problem for you.

I am undecided whether I should fix the documentation or the code.

**Comment by kontrabas380** [comment]
It works! Thank you for your answer.

**Comment by nikohansen** [comment]
Will be fixed with the next push.
