### ISSUE TITLE
Unreadable plot

### ISSUE THREAD

**Issue by TahaDz** [CMA-ES/pycma#132]
Hello,
I am using Python 3.6 , cma==3.0.3, matplotlib==3.2.1 and pycharm 
So i am trying to optimize a controller gains (3-D problem) after the execution finishes the figure does not show up(as you mentioned [here](https://github.com/CMA-ES/pycma/issues/83) ) so i tried to save it. i executed the script several times and obtained an unreadable plots :

![7-population-5-iteration](https://user-images.githubusercontent.com/30904390/81829736-1ff14e00-9533-11ea-9078-963eb5aaa258.png)

![50-population-50-iteration1](https://user-images.githubusercontent.com/30904390/81829630-051ed980-9533-11ea-84c0-8ca407ed0491.png)

This is the part of code using CMA : 
`best_solution, best_fitness = cma.fmin2(main, [0, 0, 0], 25, options={'maxiter': 15, 'CMA_elitist': True, 'bounds': [[0, 0, 0], [50, 50, 50]],'popsize':7})`
`cma.plot()`
`plt.show()`
`cma.s.figsave('execution.png')`
How can i fix this also can i just plot only the fitness function, standard deviations and the solutions?
Thank you.

**Comment by nikohansen** [comment]
It looks like several runs are displayed in the same figure, but I have no idea why (this is what I get only when I set the option `'verb_append': 1`). By default, the next run overwrites the data from the previous run.

A simple way to fix this is to not execute several runs in the same folder or with the same `'verb_filenameprefix'` option.

The `cma.CMADataLogger` class reads in logger data like
```python
logger = cma.CMADataLogger()
logger.load()
```
and now you have `logger.f`, `.std`, `.xmean`, `.xrecent` and other attributes (`list(logger.__dict__)` shows the attributes) you can investigate and/or plot. The `.xmean` attribute is in the untransformed space and hence unbounded. The transformation you could retrieve from the `gp` attribute of what you have assigned to `best_fitness`: the second output argument of `fmin2` is not the fitness, but the `CMAEvolutionStrategy` class instance with all information available on the run. The `result.fbest` attribute contains the best fitness.

**Comment by TahaDz** [comment]
That solved my problems, Thank you
