### ISSUE TITLE
Turning off warnings

### ISSUE THREAD

**Issue by Nedaaaa** [CMA-ES/pycma#133]
Hi all,

I was wondering if there is any way that I can turn off warnings from "cma.fitness_transformations" library. I am trying to use "EvalParallel" for multiprocessing and it keeps giving me the warning that "`fitness_function` must be a function, not an instancemethod, to work with `multiprocessing`".

I would appreciate it if someone can help me.

Thank you

**Comment by nikohansen** [comment]
I believe this warning should be gone with [this commit](https://github.com/CMA-ES/pycma/commit/ed33dc342fbb3369988d398c1e922242a2071c5e) as included in the [newest release 3.0.3](https://github.com/CMA-ES/pycma/releases).

```
pip install --upgrade cma 
```
should do.

**Comment by Nedaaaa** [comment]
> I believe this warning should be gone with [this commit](https://github.com/CMA-ES/pycma/commit/ed33dc342fbb3369988d398c1e922242a2071c5e) as included in the [newest release >=3.0.2](https://github.com/CMA-ES/pycma/releases).
> 
> ```
> pip install --upgrade cma 
> ```
> 
> should do.

Great, it did! Thank you.
