### ISSUE TITLE
assert len(sampler_weights) == len(pop_zero) + 1

### ISSUE THREAD

**Issue by 3kwa** [CMA-ES/pycma#135]
I am hitting that assertion running a toy optimisation and can't figure out why nor how not to?

**Comment by 3kwa** [comment]
misunderstood {"popsize": popsize} options

**Comment by nikohansen** [comment]
I am not sure to understand what "hitting" means. Did the code raise an `AssertionError`?

**Comment by 3kwa** [comment]
Yes it did but that was entirely my fault - which I realized 30 seconds after creating the issue. 

I am having a ball playing with pycma - thanks a lot!
