### ISSUE TITLE
BoundPenalty.__call__ fails when np.array given as a solution

### ISSUE THREAD

**Issue by hogloid** [CMA-ES/pycma#136]
https://github.com/CMA-ES/pycma/blob/master/cma/constraints_handler.py#L350
This condition would not work if x is a np.array, failing by `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

**Comment by nikohansen** [comment]
Thanks for the catch, it's not even clear to me why the test is needed in the first place.

**Comment by nikohansen** [comment]
Fixed with commit a1719b4 in the master branch.
