### ISSUE TITLE
n_jobs error

### ISSUE THREAD

**Issue by takahh** [CMA-ES/pycma#137]
Hi, I got an error like below when I ran in parallel in MacPro. It runs without errors on my MacBook pro, though. Without the n_jobs option, it does not fail. Any idea? Thank you.
 ——————————————-

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
(8_w,17)-aCMA-ES (mu_w=5.1,w_1=31%) in dimension 80 (seed=593545, Sun Jun  7 08:34:21 2020)
Exception ignored in: <function EvalParallel2._del_ at 0x11065fca0>
Traceback (most recent call last):
  File "/Users/mac/.conda/envs/RNP_opt/lib/python3.8/site-packages/cma/optimization_tools.py", line 304, in _del_
    self.terminate()
  File "/Users/mac/.conda/envs/RNP_opt/lib/python3.8/site-packages/cma/optimization_tools.py", line 288, in terminate
    if not self.pool:
AttributeError: 'EvalParallel2' object has no attribute 'pool'

**Comment by takahh** [comment]
Failed : Sierra
Success : Catalina

**Comment by nikohansen** [comment]
Thanks for the report. Currently I cannot reproduce the error. Could provide the result of

```python
import cma
cma.__version__
```

and the calling sequence you used when the error occurred?

**Comment by nikohansen** [comment]
`EvalParallel2.__init__` reads:

```python
    def __init__(self, fitness_function=None, number_of_processes=None):
        self.fitness_function = fitness_function
        self.processes = number_of_processes  # for the record
        if self.processes is None or self.processes > 0:
            self.pool = ProcessingPool(self.processes)
        else:
            self.pool = None
```
Hence the error
```python
AttributeError: 'EvalParallel2' object has no attribute 'pool'
```
is difficult to understand.

**Comment by takahh** [comment]
I added freeze_suport and it worked. Thank you for your time!
