### ISSUE TITLE
How to deactivate (expensive) solution archiving, was: Understanding how to optimize the truncate() function

### ISSUE THREAD

**Issue by jvita** [CMA-ES/pycma#142]
When working with larger population sizes (multiple thousands), profiling my code has shown that upwards of 75% of the runtime is being spent in the `tell()` call (I use the ask-and-tell interface). The entirety of this cost is coming from the `truncate()` call in the `insert()`  function, which happens every 10 steps by default.

I only occasionally experiment with populations of this size, but am particularly interested in them as I start moving towards multi-objective optimization with [COMO-CMA-ES](https://github.com/CMA-ES/pycomocma), which is built on top of `pycma`.

I've come up with a few different ways to fix/avoid this problem, but I wasn't sure what the most appropriate solution would be. I've considered simply `truncate()`-ing less frequently or increasing the maximum archive size (since I'm always running on supercomputing systems where there's enough RAM that the archive could probably get pretty big before being an issue), JIT-ing the `truncate()` function, or looking into re-structuring how the archive stores/inserts/deletes entries.

Do you have any thoughts on this? Is there any reason that I need to `truncate()` so frequently, assuming there aren't any memory size issues? Do you have ideas on how the archive could be restructured?

Thanks,
Josh

**Comment by nikohansen** [comment]
One possible path is to set `cma.evolution_strategy.use_archives = False`, [see here](https://github.com/CMA-ES/pycma/blob/a47716cf126d98eeb709565888ea3f8d36daa240/cma/evolution_strategy.py#L224). In principle, the archive is not necessary in the default use cases without genotype-phenotype transformations of repair of solutions generated by `ask`. Some testing would be advisable to see that this works indeed fine.

**Comment by nikohansen** [comment]
The new workaround is adding the following line:

```python
cma.evolution_strategy._CMASolutionDict = cma.evolution_strategy._CMASolutionDict_empty
```
before to instantiate `cma.CMAEvolutionStrategy` like
```python
es = cma.CMAEvolutionStrategy(x0, sigma0)
```
