### ISSUE TITLE
apparent inconsistency with mirrored samples problem

### ISSUE THREAD

**Issue by Samaritan-Infi** [CMA-ES/pycma#145]
When I use pycma, i face the problem below. 
```
 UserWarning: TPA: apparent inconsistency with mirrored samples, where dmi_div_dx0i, dm/dx0=0.459462, 0.459471 and 
dmi_div_dx1i, dm/dx1=-5.666979, -5.668783 (class=CMAAdaptSigmaTPA method=check_consistency iteration=173)
  ')')
```
What problem raised that, how could I solve it?
Thanks

**Comment by nikohansen** [comment]
Could you post the code that produces this warning? Ideally I would want to be able to reproduce the warning. I understand that this may not be possible, but without seeing the calling code sequence it is hard to say anything at all.

**Comment by Samaritan-Infi** [comment]
I'm sorry that I can only provide a part of the code for you. Thanks for your reply.
```
warnings.simplefilter("ignore", cma.evolution_strategy.InjectionWarning)
options = {'CMA_active': False, 'CMA_diagonal': True, 'popsize': 5}
es = cma.CMAEvolutionStrategy(noise.detach().cpu().numpy(), 0.5, options)
for step in range(MAX_STEP):
        noise_list = es.ask()
        # calculate_noise_score
        noise_score_list = []
        for i, noise in enumerate(noise_list):
                .....
                if success:
                          .....
                          return
                .....
                loss = calculate_loss(output, target_var, targeted)
                noise_list[i] = noise.cpu().numpy()
                noise_score_list.append(loss.item())
        es.tell(noise_list, noise_score_list)
```
follows the calculate_loss function:
```
def calculate_loss(output, target, targeted):
    # compute the probability of the label class versus the maximum other
    real = (target * output).sum(1)
    # return real if not targeted else -real
    other = ((1. - target) * output - target * 10000.).max(1)[0]
    if targeted:
        # if targeted, optimize for making the other class most likely
        loss = torch.clamp(torch.log(other + 1e-30) - torch.log(real + 1e-30), min=0.)
    else:
        # if non-targeted, optimize for making this class least likely.
        loss = torch.clamp(torch.log(real + 1e-30) - torch.log(other + 1e-30), min=0.)
    return loss
```
Can you figure out something to solve that problem?
Thanks!

**Comment by Samaritan-Infi** [comment]
I suddenly thought, maybe not related,  that the cma-es evolution directions will head to the better-score direction. If the searching space exists two extreme points, It will converge to one of them or both?

**Comment by nikohansen** [comment]
Thanks, that helps already, could you also post the resulting picture of

```python
from matplotlib.pyplot import savefig
import cma

cma.plot()
savefig('tpa-bug')
```

executed in the same folder as the experiment? That would be a very good sanity check to figure out what is happening.

Then:

- I would strongly advise against a population size of `5`, it is quite suboptimal in particular in large dimension. Stick with the default or at least `10`. I don't think this will fix the warning, but it might. In a noisy scenario, tiny population sizes are even more disadvantageous.

- using `'AdaptSigma': cma.sigma_adaptation.CMAAdaptSigmaCSA` will avoid the warning. I am not convinced that it will improve the results though (though it might).

- the evolution strategy converges only to one optimum and in a noisy scenario it is also not likely to converge in a mathematical sense.

**Comment by Samaritan-Infi** [comment]
Thanks for your reply.

It triggered another problem. I tried the `cma.plot()` function and raise the error below
```
  File "/home/yf/adversarial/MetaAttack/cifar/cifar_gen_grad_for_meta/attacks/cma_attack.py", line 178, in cma_attack
    cma.plot()
  File "/home/yf/anaconda3/envs/bishe/lib/python3.7/site-packages/cma/logger.py", line 1499, in plot
    x_opt, fontsize, downsample_to, xsemilog, addcols, **kwargs)
  File "/home/yf/anaconda3/envs/bishe/lib/python3.7/site-packages/cma/logger.py", line 666, in plot
    if self.f.shape[0] > downsample_to:
AttributeError: 'CMADataLogger' object has no attribute 'f'

Process finished with exit code 1
```
Does that means that my cma needs to upgrade?

+ About the parameter `popsize`, I understand what you mean. But I tried popsize several times from 2 to 50 to adjust my task, and 5 performs the best. The task is to generate noise to build an adversarial image example to confuse a CNN model. I used 
py-cma to generate noise. Maybe you can help me explain the strange scenario?

+ I tried it and it worked. 

Really Thanks!

**Comment by nikohansen** [comment]
> I tried the cma.plot() function and raise the error below

OK, I guess it's more consistent to use
```
es.logger.plot()
```
for plotting instead of `cma.plot()`. Does that work?

> I used py-cma to generate noise. The dimension of the noise is 1-d tensor in the range from 100 to 300. 

To me it's not so clear what the loss/score function is though.

> when I set the CMA_diagonal : True and the es.C = 1. Does that mean that my co-variance matrix of the process keeps 1 during the process?

No, in the case when the covariance is diagonal, `es.sm.C=1` and its standard deviations are stored via `es.sigma_vec` instead. The sample covariance matrix is `es.sigma**2 * S * es.sm.C * S` where `S` is the diagonal matrix from `es.sigma_vec.scaling`.

**Comment by Samaritan-Infi** [comment]
Thanks， really help me a lot.

**Comment by Samaritan-Infi** [comment]
Sorry, I found the error still appeared when using `es.logger.plot()`
The log is below
```
 File "/home/yf/adversarial/MetaAttack/cifar/meta_attack_cifar/attack_main.py", line 198, in <module>
    main(device)
  File "/home/yf/adversarial/MetaAttack/cifar/meta_attack_cifar/attack_main.py", line 192, in main
    attack(model, test_loader, meta_distribution_model, meta_gradient_model, surrogate_model_list)
  File "/home/yf/adversarial/MetaAttack/cifar/meta_attack_cifar/attack_main.py", line 136, in attack
    targeted=not args.untargeted)
  File "/home/yf/anaconda3/envs/bishe/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/yf/adversarial/MetaAttack/cifar/meta_attack_cifar/attacks/cma_attack.py", line 215, in cma_attack
    es.logger.plot()
  File "/home/yf/anaconda3/envs/bishe/lib/python3.7/site-packages/cma/logger.py", line 666, in plot
    if self.f.shape[0] > downsample_to:
AttributeError: 'CMADataLogger' object has no attribute 'f'
```
Did I miss something to initialize?

```
warnings.simplefilter("ignore", cma.evolution_strategy.InjectionWarning)
    options = {'CMA_active': False, 'CMA_diagonal': True, 'popsize': POPSIZE, 'AdaptSigma': cma.sigma_adaptation.CMAAdaptSigmaCSA}  # {'CMA_diagonal': True, 'CMA_active': False}
    es = cma.CMAEvolutionStrategy(noise.detach().cpu().numpy(), 1, options)
```
Thanks a lot!

**Comment by demipixel** [comment]
Not totally related to the issue, but if you're getting the above issue plotting, it may be worth:

1) Add `es.logger.add()` after your generation (e.g. your `.tell()` line).
2) If a plot doesn't show up, `from matplotlib import pyplot` at the top and then after your `es.logger.plot()`, add `pyplot.show()`
3) Wait a ~3 generations (I'm guessing it just doesn't have enough data at the start?)

**Comment by Samaritan-Infi** [comment]
Thanks, that really helps me a lot
