### ISSUE TITLE
What to use instead of string for x0?

### ISSUE THREAD

**Issue by sergeyf** [CMA-ES/pycma#146]
Hello,

Before a recent version I used to call `fmin` as follows:

```
    lower_bounds = np.array([0, 0 ,0])
    upper_bounds = np.array([1, 1, 1])
    result = cma.fmin(
        loss_function,
        f'np.random.uniform({list(lower_bounds)}, {list(upper_bounds)})', 
        std,
        {
            'bounds': [lower_bounds, upper_bounds],
            'popsize': popsize,
            'verbose': -9,
            'CMA_stds': upper_bounds / 4
        },
        restarts=restarts,
        bipop=True
    )
```

Now, however I am getting errors that x0 can no longer be a string. What is the right way to get a random init for each restart? The documentation still says "use a string".

Thanks for the great package!

**Comment by nikohansen** [comment]
Damn, the documentation is wrong ;-)

The error message gives a hint though:
```python
ValueError: x0 may be a callable, but a string is no longer permitted
```
Using 

```
lambda : np.random.uniform(lower_bounds, upper_bounds)
```
in place of 
```
f'np.random.uniform({list(lower_bounds)}, {list(upper_bounds)})'
```
seems to work for me.

**Comment by sergeyf** [comment]
Thank you :)

The convenience is truly minor compared to the hugely wonderful package itself!
