### ISSUE TITLE
Does each iteration update a new solution?

### ISSUE THREAD

**Issue by R2h1** [CMA-ES/pycma#149]
![image](https://user-images.githubusercontent.com/40930301/95413883-214a6980-095f-11eb-855e-4148d5fca22d.png)

**Comment by R2h1** [comment]
Excuse me, is the loss function value recorded during each iteration, or is it recorded during each function evaluation?

**Comment by R2h1** [comment]
![image](https://user-images.githubusercontent.com/40930301/95414971-9e76de00-0961-11eb-8492-c92a2c853b0d.png)

**Comment by R2h1** [comment]
The ask interface will return multiple candidate solutions, and each candidate solution will perform function (loss function) evaluation calculation, whether to record the function evaluation value of the candidate solution (loss function)？

**Comment by nikohansen** [comment]
Sorry, I don't understand the question. What do you mean by "recorded"? `[objective_function(x, *args) for x in X]` computes the objective function value for each solution and places the values in a list which is passed to `tell`.
