### ISSUE TITLE
FutureWarnings in some comparisons

### ISSUE THREAD

**Issue by MichaelClerx** [CMA-ES/pycma#15]
Hello! Trying out CMAES for some biological optimization problems. It works well, but I do get a bunch of warnings:

```
/usr/lib/python2.7/site-packages/cma.py:956: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if bounds in (None, [None, None]):
```

```
/usr/lib/python2.7/site-packages/cma.py:2937: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if x0 == str(x0):
```

Using Python 2.7.13 and CMAES 1.1.07 (from pip)

**Comment by nikohansen** [comment]
Thanks for the report, the second issue should be resolved in the current code on github. I am not sure for the first. As I don't get the warning, any idea how I can make sure to see the warnings? I tried `warnings.simplefilter('always')` to no avail.

**Comment by MichaelClerx** [comment]
Thanks! I only get the second warning when I use bounds (`options = cma.CMAOptions(); options.set('bounds', [lower, upper])`

**Comment by MichaelClerx** [comment]
In version 2.3.1, calling `options.set('bounds', [numpy.array(lower), np.array(upper)])` causes a `ValueError` to be triggered from the line `if bounds in (None, [None, None]):`. It goes away if you convert the numpy arrays to lists!

**Comment by nikohansen** [comment]
I only see a comparison warning and possibly value error due to non-consistent values between the bounds and `sigma`. Can you paste the error message?

**Comment by MichaelClerx** [comment]
Sorry! Happened on a colleague's system. Trying to reproduce it now I only get this warning:

``
`/usr/lib/python2.7/site-packages/cma/constraints_handler.py:113: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if bounds in (None, [None, None]):
```

Again, it goes away when converting the lower and upper bounds to lists first
