### ISSUE TITLE
multiple equality constraints 

### ISSUE THREAD

**Issue by kennybix** [CMA-ES/pycma#150]
I defined a constraint function such that the sum of the each row is equal to 1:
```  
def constraint_func(weight_matrix): 
        w = np.array(weight_matrix)   
       row_sum = []
       for i in range(row_count):
        row_sum.append(w.sum(1)[i] - 1)
        return w_d
```

then used it within my optimization line

```
xopts, es = cma.evolution_strategy.fmin_con(objective_function, start_point, 0.1, h=lambda xk:np.array(constraint_func(xk)), \
                options={'bounds':new_bounds,'verbose':-9,'ftarget':1e-5, 'popsize':40})
```
but this did not get the expected results. The conditions were not met because the sum of each row was not equal to 1

For example, I got this:

[[0.48587607,0.21321718,0.26050714,0.35083342]
 [0.17126094,0.01050724,0.20344696,0.3419946 ]]
The sum of weights on each row did not meet the intended criteria

**Comment by nikohansen** [comment]
Thanks for the notification. There is not much I could say or do from the provided information. I don't even know what

```
[[0.48587607 0.21321718 0.26050714 0.35083342]
[0.17126094 0.01050724 0.20344696 0.3419946 ]]
```
is and what is wrong with it.

Showing the plots from

```python
es.logger.plot()
es.objective_function_complements[0].logger.plot()
```
may already help a quite a bit.

**Comment by nikohansen** [comment]
It looks like you should remove `'ftarget'` from the options list. On that note: a verbosity of -9 is a pretty bad idea when something is apparently not exactly going according to plan.

**Comment by kennybix** [comment]
removing 'ftarget' did the work. Thank you so much
