### ISSUE TITLE
Is standardization of objective outcomes important for pycma

### ISSUE THREAD

**Issue by a-z-e-r-i-l-a** [CMA-ES/pycma#159]
I have an objective function with mean and standard deviation are approx. 10 and 0.1. 

Would it be necessary or effective, to have this objective normalized or standardized (mean zero and standard deviation of 1) for better optimization performance of pycma?

**Comment by nikohansen** [comment]
No, a monotonous transformation of the objective function value (like a shift or scaling) does not change the performance. It may change when the algorithm will terminate.
