### ISSUE TITLE
Set `tolfun` to `1e-6`, but get result with `f=7.3`

### ISSUE THREAD

**Issue by MichaelClerx** [CMA-ES/pycma#16]
I'd like to specify a minimum value of the score function of 1e-6. To this end I've added an options object:

```
options = CMAOptions()
options.set('tolfun', 1e-6)
```

When I run the optimiser on a toy problem, it returns almost immediatly with

```
termination on tolfun=1e-06
final/bestever f-value = 7.289226e+00 7.289226e+00
incumbent solution: [310.65090759643533, 313.64377551885428]
std deviation: [232.16677605865451, 235.91773080927337]
```

Am I doing something wrong? If I run without setting `tolfun` it returns an `f=1.5e-11` within seconds!

**Comment by MichaelClerx** [comment]
Ok, from the code it seems the tolerance is in change of f per iteration, not absolute value.
Woops!

**Comment by nikohansen** [comment]
The "right" option is named `'ftarget'`, `'tolfun'` is indeed referring to a tolerance between f-values.

**Comment by MichaelClerx** [comment]
Thanks!
