### ISSUE TITLE
Seach for optimum in discrete space

### ISSUE THREAD

**Issue by a-z-e-r-i-l-a** [CMA-ES/pycma#160]
Is there any method or heuristic that you may suggest may be best for optimizing discrete parameters using py_cma

**Comment by nikohansen** [comment]
I think it also very much depends on the type of problem. For integer variables the `'integer_variables'` option is a (not very sophisticated) possibility.
```python
import cma
cma.CMAOptions('integ')
```
```
{'integer_variables': '[]  # index list, invokes basic integer handling: prevent std dev to become too small in the given variables'}
```

**Comment by a-z-e-r-i-l-a** [comment]
does it allow optimization of discrete and continuous parameters simultaneously?

 is there possibly an example for it? like how we can extend the api we use now for continuous space to also have discrete parameters optimization:

```
        cma = cma.CMAEvolutionStrategy(
            x0=[.5] * 3, 
            sigma0=.166,
            inopts={
                    'bounds': [0, 1],
                    'maxfevals': 1000,
                    'popsize': 2,
                    'verb_log': 0,
                    'seed': self.seed + 2,
                    },
```

**Comment by nikohansen** [comment]
See issue https://github.com/CMA-ES/pycma/issues/177 for how to use the `integer_variable` option.
