### ISSUE TITLE
Speed of EvalParallel2

### ISSUE THREAD

**Issue by jsadet** [CMA-ES/pycma#161]
Hello,

First of all, thank you for your code. 

I have a question about the EvalParallel2 class. When I compare the performance of this class with a mono processing optimisation, I end up with a faster optimisation with the mono processing, whatever the combination of popsize or dimensionality of the optimised function used. Usually, the gap is about 30s.

Here, I have used a rather simple function (Sphere function) to optimise but I am interested in the optimisation of multimodal and non-stationary functions stemming from an acquisition function (Expected Improvement in Bayesian Optimisation). These functions are characterised by several bowl shaped behaviour in some areas and constant behaviour in most areas of the design space. From my preliminary tests, an important population size seems to work well and converges toward global optimum but the computational cost becomes prohibitive. Hence, parallel evaluation seems to be a good workaround.

Thus, have you got any insight on how is it possible that EvalParallel2 is slower than mono processing ? Here is a bit of code from one of my tests.

[test_parallel.txt](https://github.com/CMA-ES/pycma/files/5844168/test_parallel.txt)

Regards,
Jérémy SADET

**Comment by nikohansen** [comment]
Parallel evaluations only help on "expensive" objective functions, because the overhead for the distribution must be more than offset by computing the function values in parallel. In the attached file you tried pretty much on the cheapest-possible-to-compute function.

I think you can also not expect a gain much above and beyond the number of cores on your machine, regardless of the population size.

This function should run faster when parallelized:

```python
import time
def sphere_slow(x):
    time.sleep(0.1)
    return sum([xi**2 for xi in x])
```

**Comment by jsadet** [comment]
I didn't thought about this. I have tested your sphere_slow function and actually, EvalParallel2 is better than monoprocessing.

26 min (Monoproc)
3min (10 workers)
1min30s (20 workers)
46s (40 workers)

Nevertheless, as you point it out, the improvement is not interesting since with the non-delayed sphere function, the algorithm converges in 4 seconds.

Thanks for your answer !
