### ISSUE TITLE
Stop after a number of rejected evaluations

### ISSUE THREAD

**Issue by scarlehoff** [CMA-ES/pycma#163]
It would be nice to have in methods such as `ask_and_eval` a `max_eval` variable to stop after a certain maximum number of evaluations is reached (for instance, because many solutions were rejected due to NaNs).

I know that per the [docs](http://cma.gforge.inria.fr/apidocs-pycma/cma.evolution_strategy.CMAEvolutionStrategy.html#rst-examples) the same behavior can be obtained "manually" but it would be a nice feature for convenience.

**Comment by nikohansen** [comment]
`ask_and_tell` does only `popsize` evaluations in general. To limit the number of `NaN`, a good approach may be to write a wrapper around the objective function. Just limiting the number is not a well enough prescription of an algorithm, as a decision needs to be taken which value to assign instead of `NaN`.

**Comment by scarlehoff** [comment]
I meant it as a timeout, for convenience. The same behaviour can be achieved in other ways of course.

**Comment by nikohansen** [comment]
All candidate solutions are sampled independently. If we "fail" to sample a feasible solution for one candidate, we fail for all other candidate in the same way of whatever "fail" means. As a consequence, we need to change the sample distribution and, to be on the safe side, restart the current iteration. My thoughts of possible actions:

- check whether the mean is feasible
- set the mean to any solution from the last iteration (all solutions are feasible here)
- decrease the step-size

**Comment by nikohansen** [comment]
Termination on too many infeasible solutions can be implemented like so:

```python
import numpy as np
import cma

def is_feasible(f):
    """define feasiblity"""
    return f is not None and not np.isnan(f)

class Feasible:
    """deliver termination condition depending on feasibility count"""
    def __init__(self, maxreevals=1e4, _is_feasible=is_feasible):
        self.maxreevals = maxreevals
        self._is_feasible = _is_feasible
        self.count = 0

    def __call__(self, x, f):
        """modify feasibility decision depending on count"""
        if self.count > self.maxreevals:
            return True
        if not self._is_feasible(f):
            self.count += 1
            return False
        self.count = 0
        return True

    def stop(self, *args):
        """return True when more than maxreevals infeasible solutions occured in a row"""
        if self.count > self.maxreevals:
            return self.count
        return False

feasible = Feasible(15)  # terminate when more than 15 infeasible solutions
                         # are evaluated in a row

x, es = cma.fmin2(cma.fitness_transformations.SomeNaNFitness(
                      cma.ff.sphere, 0.5),
                  3 * [1], 1,
                  {'is_feasible': feasible,
                   'termination_callback': feasible.stop
                   })
        
```
