### ISSUE TITLE
BIPOP and parallelization

### ISSUE THREAD

**Issue by enajx** [CMA-ES/pycma#165]
Is there a way to run BIPOP while parallelising over many threads?

`fmin` provides the option to run BIPOP but does not provide `n_jobs` flag, while `CMAEvolutionStrategy` provides `n_jobs` flag but doesn't have a BIPOP option.

**Comment by nikohansen** [comment]
The easiest way may be to manually factor out the BIPOP code from `cma.fmin` and call `CMAEvolutionStrategy.optimize` with the `n_jobs` option.

A general problem though is that this only parallelizes a single population, whereas in the small-population runs of the BIPOP scheme one may want to parallelize several populations. The code of [`CMAEvolutionStrategy.optimize`](https://github.com/CMA-ES/pycma/blob/4390ec35f3bd81925e147fdc781734bb9047e343/cma/interfaces.py#L121) is just a few lines, so parallelizing several populations along the lines of this code doesn't look too difficult either.
