### ISSUE TITLE
Please add few jupyter notebooks in example section.

### ISSUE THREAD

**Issue by ajikmr** [CMA-ES/pycma#166]
It will be great to have three-four jupyter notebooks in example section. For me, many options are not working otherwise, lets say cma.plot() . Notebooks could be an easy starting point for personal use.

**Comment by nikohansen** [comment]
Indeed, that's a good point!

**Comment by nikohansen** [comment]
Is there a preferred way how Jupyter notebooks should be published on GitHub?

**Comment by ajkmr-data** [comment]
'pyswarms' package has some example notebooks at https://github.com/ljvmiranda921/pyswarms/tree/master/docs/examples .
Here same style can be followed as it will help users in getting started with pycma

**Comment by nikohansen** [comment]
Can be found at https://github.com/CMA-ES/pycma/tree/master/notebooks, see also #188
