### ISSUE TITLE
a slight confusion regarding fmin_con

### ISSUE THREAD

**Issue by pierepier** [CMA-ES/pycma#174]
Hi, I'm trying to use the CMA method to numerically solve covariance matrixes for experiments, thus I have a minimum of 14 variables and a single integer n for the cluster size which isn't iterable but I had to write it as [n] for the code to function, I was first wondering if that is an issue since n by nature isn't iterable. and Secondly, I would also limit the values in the array I get as an answer to be larger than zero but that doesn't seem to be an option, could I please get some help with that ?

Best regards

**Comment by nikohansen** [comment]
I admit that I don't quite understand several things in the question. I don't know what "numerically solve covariance matrixes" means. I don't understand what "I had to write it as [n] for the code to function" refers to (and to which code) and hence I don't understand for what this could be an issue. I don't understand which array/answer you mean if you write "limit the values in the array I get as an answer".

Possibly, posting the code you use to interface the `cma` module (and in case the output) may help as well.

**Comment by pierepier** [comment]
I have tried the method from case  #94 before but I get a syntax Error when applying it. There also Is the possibility that I'm doing it wrong. Observe below.
 out=cma.fmin(optimizationfunction,pump,0.2,args=(n,),{'bounds':[0,50]})

**Comment by pierepier** [comment]
I'm sorry to bother you I started to work subsequently on other aspects of the code but could you perhaps help me out and show me what variant could exactly give the optimal results in this case? I'm quite new to python and still quite lost in this regard. :)
