### ISSUE TITLE
Optimising discrete variables

### ISSUE THREAD

**Issue by enajx** [CMA-ES/pycma#177]
Is there an natural way of optimising parameters over a discrete space? eg. integer space = {-1,0,1}

The integer_variables option `'integer_variables' : [-1,0,1]` seems to be ignored by the sampler and still suggests non-integer variables.

There seem to be some research on using CMAES for discrete optimisation but no implementation seems to be available: [A discrete version of CMA-ES - arXiv](https://arxiv.org/abs/1812.11859)

**Comment by nikohansen** [comment]
EDIT: integer variables now deliver solutions with only integer values. To get only values -1, 0, 1, the lower and upper bound can be set to -1 and 1.

The option `'integer_variables'` asks for an index list of _variables_ which shall be "treated as" integer, it does not indicate the allowed _values_ of the variables (which is by default all integers/values).

The current documentation is indeed poor: in the computation of the objective function (or in a wrapper around the objective function), the user still also has to make sure to "interpret" the variables as integers, like by taking the `np.floor(x)` ~`int(x[i])`~ before `x` enters the computation.

Then, using the `bounds` option will limit the value range (probably you want a range from `-1` to `2-1e-9` when the `floor` is taken, to get the values -1, 0, 1 with similar "weight").

**Comment by nikohansen** [comment]
FTR, a much better integer handling is now default since [`v4.0.0`](https://github.com/CMA-ES/pycma/commit/0086ab4cf70db09917bf4c435258c2aaba769a1f).
