### ISSUE TITLE
 FutureWarning results in errors when the last version of numpy is used.

### ISSUE THREAD

**Issue by DSamuylov** [CMA-ES/pycma#18]
There are these two warning that appear when you call `fmin` function:

> ...python2.7/site-packages/cma.py:2938: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
>   if x0 == str(x0):
> ...python2.7/site-packages/cma.py:957: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
>   if bounds in (None, [None, None]):

I just updated `numpy` to the newest version and now `cma` breaks at those points. I had to uninstall it and install an older version of `numpy` to be able to run the code that I have. Anyone could fix the issue?

**Comment by nikohansen** [comment]
I assume you are using the module installed via `pip` (single file `cma.py`). The issue should be fixed if you install from the current master branch of this repository.

**Comment by DSamuylov** [comment]
Thank you a lot for your prompt reply! Indeed I did the installation using `pip`. I will test it and if I have any problem I will report.

**Comment by nikohansen** [comment]
I assume this is solved, otherwise please reopen.
