### ISSUE TITLE
Separable CMA does not take "CMA_stds" into account

### ISSUE THREAD

**Issue by vineethk** [CMA-ES/pycma#181]
The following applies to version `3.1.0` (at least). It looks like `"CMA_stds"` option is taken into account when `"CMA_diagonal"` is `False`, but not taken into account when `"CMA_diagonal"` is `True`.

Consider the example below.

```python
import cma  # version: 3.1.0

def print_points(stds, diagonal):
    options = {
        "seed": 2,
        "bounds": [[0, 0], [100, 1000]],
        "CMA_stds": stds,
        "CMA_diagonal": diagonal,
    }
    opt = cma.CMAEvolutionStrategy([10, 100], 1.0, options)
    print(opt.ask())


print_points([1, 1], True)     # 1
print_points([1, 100], True)   # 2
print_points([1, 1], False)    # 3
print_points([1, 100], False)  # 4 
```

`#1` and `#2` print the same points, even though different `"CMA_stds"` are provided (`"CMA_diagonal"` is `True`). However, as expected, `#3` and `#4` print different points (`"CMA_diagonal"` is `False`).

Upon looking at the [source code](https://github.com/CMA-ES/pycma/blob/880d83a7cb3f0974b9b3a80ce9c1311f2746b692/cma/evolution_strategy.py#L1619), it seems we might have to use `"CMA_teststds"` when `"CMA_diagonal"` is `True` to get around this issue? That is, the following code takes per-dimension stds into account.

```python
import cma  # version: 3.1.0

def print_points(stds, diagonal):
    options = {
        "seed": 2,
        "bounds": [[0, 0], [100, 1000]],
        "CMA_stds": stds,
        "CMA_diagonal": diagonal,
    }
    if diagonal:
        options["CMA_teststds"] = stds
    opt = cma.CMAEvolutionStrategy([10, 100], 1.0, options)
    print(opt.ask())


print_points([1, 1], True)     # 1
print_points([1, 100], True)   # 2
print_points([1, 1], False)    # 3
print_points([1, 100], False)  # 4 
```

Perhaps the behavior in the first code snippet is buggy?

**Comment by nikohansen** [comment]
Thanks for the report, I can reproduce the behavior. Ignoring `CMA_stds` in the `CMA_diagonal` case is indeed a bug. I'll fix it.

In any practical application, I suggest to transform the objective function with `cma.fitness_transformations.ScaleCoordinates` rather than using the `CMA_stds` option.
