### ISSUE TITLE
Using EvalParallel2 with a fitness function that has several arguments

### ISSUE THREAD

**Issue by florencegarcialaunay** [CMA-ES/pycma#183]
Hi Nikohansen,

I already use for some time pycma in order to optimize an objective function which involves high CPU. 
Therefore I would like to parrallelize the optimization and found some interesting information about EvalParallel2. 

Before working with my own objective function, I have tried to reproduce one example that you provided, and which I remind below.
Here is the code that I used, and that works fine 

```
import time
from cma.fitness_transformations import EvalParallel2
import cma
import numpy as np
from numpy.random import randn

multip = 20
size = 8 * 20
w = np.array([1, 2, 3, 4, 5, 4, 3, 2] * multip)

def get_fitness(x):
    for i in range(1000):
        y = randn(345)
    return np.sum((x - w) ** 2)

n_proc = 0
for n_proc in range(1, 12):
    es = cma.CMAEvolutionStrategy([0] * size, 1)
    time1 = time.time()
    with EvalParallel2(get_fitness, number_of_processes=n_proc) as eval_all:
        while not es.stop():
            X = es.ask()
            es.tell(X, eval_all(X))
    time2 = time.time()
    # eval_all also accepts `fitness_function`
    # and `args` as optional arguments
    print(str(n_proc) + " processes et %s seconds " % (time2 - time1))
    print(es.result[1])
```

Now to go further before implementing it for my objective function, I would like to check a case in which the get_fitness function has other arguments than x, which I do not want to include to tested solutions. Here is the code that I tried. 

```
def get_fitness(x, ab):
    for i in range(1000):
        y = randn(345)
    return np.sum((x - w) ** 2) + ab

a = 2
n_proc = 0
for n_proc in range(1, 12):
    es = cma.CMAEvolutionStrategy([0] * size, 1)
    time1 = time.time()
    with EvalParallel2(get_fitness, number_of_processes=n_proc) as eval_all:
        while not es.stop():
            X = es.ask()
            es.tell(X, eval_all(X, args=a))
    time2 = time.time()
    print(str(n_proc) + " processes et %s seconds " % (time2 - time1))
    print(es.result[1])
```

Here is the error that I get.
```
(9_w,19)-aCMA-ES (mu_w=5.6,w_1=29%) in dimension 160 (seed=867691, Thu Nov 25 12:03:45 2021)
Traceback (most recent call last):
  File "Essai_parallel_cma.py", line 28, in <module>
    es.tell(X, eval_all(X, args=a))
  File "/usr/local/lib/python3.7/site-packages/cma/optimization_tools.py", line 290, in __call__
    for x in solutions]
  File "/usr/local/lib/python3.7/site-packages/cma/optimization_tools.py", line 290, in <listcomp>
    for x in solutions]
TypeError: can only concatenate tuple (not "int") to tuple
```

My guess is that I do not adequately pass the information about the other argument of the get_fitness function. But I tried several codes, without success. 
Could you indicate me if it is feasible to pass some other arguments to the objective function and if yes how to do this correctly? 
Best regards,

Florence

**Comment by nikohansen** [comment]
A quick suggestion: try `args=(a,)` instead of `args=a`.

**Comment by florencegarcialaunay** [comment]
Many thanks Nikolaus for quick answer ! 
It works just fine.
I also made the modification and succeeded in parallelizasing my CPU-expensive objective function !
Once again many thanks !
Have a nice evening,

Florence
