### ISSUE TITLE
Usage of x0

### ISSUE THREAD

**Issue by cmakl** [CMA-ES/pycma#189]
Am I right in thinking that `x0` is never evaluated? 
What's the reasoning behind this? Seems counterintuitive to me. 
If we already have an idea for a good starting point, shouldn't the algorithm evaluate `x0` and start the search from there?
Maybe the search starts from `x0`, just the function is not evaluated at `x0`?

Thanks

**Comment by nikohansen** [comment]
`x0` is the initial solution of the search and it is not evaluated by the algorithm.
 
 The user can evaluate `x0` on their own and often has (given it is a "good" starting point, it has to have been evaluated to determine that it is "good"). Hence its re-evaluation would generally be wasteful.

**Comment by cmakl** [comment]
Understood. Thank you for the prompt answer.
