### ISSUE TITLE
Is there any efficient way for using cma-es for categorical variables?

### ISSUE THREAD

**Issue by gloaming2dawn** [CMA-ES/pycma#194]
Hi, CMA-ES is a well-known algorithm, however it only supports for numerical variables. In real world tasks, there is always many categorical parameters need to be optimized.

I want to know whether is there an efficient way to use CMA-ES for categorical variables. Using one-hot encoder is a naive way which is not efficient enough in high categorical dimensions.

**Comment by nikohansen** [comment]
I am pretty sure there is (a least currently) no generic, efficient solution in the context of CMA-ES. There is a paper that tries to address integer variables https://hal.inria.fr/file/index/docid/629689/filename/RR-7751.pdf As far as I know it is only implemented in Matlab/Octave and I wouldn't consider it as a production version of an algorithm.
