### ISSUE TITLE
BBOB problems with zerox=True

### ISSUE THREAD

**Issue by sedefe** [CMA-ES/pycma#200]
Setting the `xopt` to zero does not work for BBOB functions F9, F19, F20, F24.
```python
import numpy as np
import cma.bbobbenchmarks as bbob

dim = 2
for number in range(1, 25):
    f: bbob.BBOBFunction = getattr(bbob, f'F{number}')(zerox=True, zerof=True)
    
    xopt = np.zeros(dim)
    fopt = f(xopt)
    
    if not fopt == f.fopt:
        print(f'[F{number}] fopt should be {f.fopt}, got {fopt:.5f}')
```
It gives:
```
[F9] fopt should be 0.0, got 6.50000
[F19] fopt should be 0.0, got 0.25037
[F20] fopt should be 0.0, got 4.18983
[F24] fopt should be 0.0, got 27.40424
```

**Comment by sedefe** [comment]
Dear namesake, thanks for your comments!

I'm doing some experiments with linear combinations of BBOB functions. It needs to set their `xopt`-s to the same point, that's why I've tried to use `zerox=True` first.
Since it did not work as expected, now I have to perform these shifts in a more weird way.

However, I suggest, you can consider some kind of warning message if the user calls `zerox=True` for unsuitable function classes.

**Comment by nikohansen** [comment]
Good point, I will implement the warning for the next release.
