### ISSUE TITLE
feedForResume

### ISSUE THREAD

**Issue by fakhreddinemami** [CMA-ES/pycma#202]
Hello,

The feedForResume function, it uses rglen((X) / popsize) to get the range of (X) / popsize. However, X is the list of solutions from previous trial and popsize is an integer. As a result, it gives the following error:

'unsupported operand type(s) for /: 'list' and 'int'' 

I am not sure if my understanding is not right or this is an issue with the code.

Thank you

**Comment by nikohansen** [comment]
Thanks for the report! I guess this refers to the `CMAEvolutionStrategy.feed_for_resume` method, and it certainly looks like a bug. The line should read
```python
for i in range(int(len(X) / popsize)):
```

**Comment by nikohansen** [comment]
Some test(s) covering this method should be added in its docstring.
