### ISSUE TITLE
facing issue in using scaling_of_variables cma es for my problem.

### ISSUE THREAD

**Issue by pramodiisc** [CMA-ES/pycma#210]
I am having a function f(x1,x2,x3,x4,x5,x6) that has to be minimised for the variable x1,x2,x3,x4,x5,x6. The range for the variables or the search domain is 
x1 (300 to 1500),
x2 (0-10),
x3 (300 to 1500),
x4(0-10) ,
x5 (500 to 20000),
x6 (0-200)
which means the algo should search for variable falling in this range.

 I am getting the function value from a simulator. 

help(cma.fitness_transformations.ScaleCoordinates) is not clear to me how can I use it for my problem.

sigma0 
scalar, initial standard deviation in each coordinate. sigma0 should be about 1/4th of the search domain width (where the optimum is to be expected). The variables in objective_function should be scaled such that they presumably have similar sensitivity. See also option scaling_of_variables.

if I am not usingcaleCoordinates I  can not use sigma 0 bigger than 10  (x4(0-10) ) which is making the algo not searching in wider domain.

Can you please share or show any simpler example.

**Comment by nikohansen** [comment]
One typical approach is to scale the variables such that the above domain is sent to the interval [0, 1] in each variable (e.g. with [ScaleCoordinates](https://cma-es.github.io/apidocs-pycma/cma.fitness_transformations.ScaleCoordinates.html), for the first variable we would put `multipliers = 1200, zero = -300/1200` such that `0 -> multipliers * (0 - zero) = 300` and `1 -> multipliers * (1 - zero) = 1500`), however see also [these practical hints](https://cma-es.github.io/cmaes_sourcecode_page.html#practical). After that, the search is bounded to the domain [0,1]. Example code to pass domain boundaries is given in the [basic use cases notebook](https://github.com/CMA-ES/pycma/blob/development/notebooks/notebook-usecases-basics.ipynb) under **Options and Bound Constraints**.

This example suggests though that `ScaleCoordinates` could be implemented with a more user friendly interface.

**Comment by nikohansen** [comment]
Addressed with commit 5ac2a14
