### ISSUE TITLE
Clarifications on logger

### ISSUE THREAD

**Issue by yhl48** [CMA-ES/pycma#211]
I have multiple questions on how to obtain the logger data. 

What does `fit` actually mean in `logger.data['f]'` and with what metric?
https://github.com/CMA-ES/pycma/blob/ac4a913b4f2c0ff61c18ee29695bbe732a3828d3/cma/logger.py#L73

In the code snippet below, how do I get the `f` values from all iterations from logger.data? Note that self._model is an instance of `CMAEvolutionStrategy`
```
while not self._model.stop():
    X = self._model.ask()
    f = [self._eval_loss(x) for x in X]
    self._model.tell(X, f)
    self._model.logger.add()
```

**Comment by nikohansen** [comment]
The columns in `outcmaes/cmafit.dat` are
```
% # columns="iteration, evaluation, sigma, axis ratio, bestever, best, median, worst objective function value, further objective values of best"
```
and these are the values in each row of the `f` attribute/key which is a `numpy` array. That is, the best f-value in each iteration would be `logger.data['f'][:, 5]` or equivalently `logger.f[:, 5]`. It may be necessary to call `logger.load()` beforehand.
