### ISSUE TITLE
Question: Implementation of outcome constraint in cma-es

### ISSUE THREAD

**Issue by pehzet** [CMA-ES/pycma#212]
Hey,
I am working on a simulation-based optimization use case with the following characteristics:
- one primary objective (costs) which should be minimized.
- one secondary objective (service-level) which is only valid with a value >0.95
- 20-200 continuous parameters (depending on the experiment configuration) where one half has bounds [0,10] and the other one [0,100]
- objective evaluation takes 2-3 seconds

Does anyone know how to implement the second objective function as an outcome constraint in cma-es? Is it even possible with cma-es? 
Removing "invalid" suggestions after the evaluation would be too inefficient with regard to the evaluation time and incrementing the costs with a penalty when the service-level is too low does not meet the use case.

Thank you in advance!

Phil

**Comment by nikohansen** [comment]
`cma.fmin_con2` takes a constraints vector-valued function as argument which is meant to be `<= 0` if feasible and could in this case return `[0.95 - secondary_objective(x)]` when `x` is its input. The constraints handling relies however on some smoothness of the two objectives close to the optimum.
