### ISSUE TITLE
is lmm CMA-ES supported by the currrent version?

### ISSUE THREAD

**Issue by mhn226** [CMA-ES/pycma#217]
Hi,

I'm new to CMA-ES in general and lmm CMA-ES in particular. Am I wrong to say that lmm CMA-ES  is not yet implemented or there is a way to use it from your current version? It seems to me that lmm CMA-ES is mentioned very rarely.

Thank you,
Ha

**Comment by nikohansen** [comment]
Hi, correct, lmm CMA-ES is not implemented in this module, only [lq-cma](https://cma-es.github.io/lq-cma/) is. The plan is to have in near future a `fmin_lq_surr` function for a smoother user experience in using lq-CMA-ES.
