### ISSUE TITLE
Bounds seem to have strange effect on population mean

### ISSUE THREAD

**Issue by david-woelfle** [CMA-ES/pycma#229]
Hi everyone,
first thank you very much for providing this repo to the community!
I am currently using pycma with "warmstarting"  and found some strange behaviour. First this is my basic setting:
```python
import cma
import numpy as np

x0 = np.asarray(
    [0.03, 0.04, 0.05, 0.5, 2.0, 3.0]
)
es = cma.CMAEvolutionStrategy(x0=x0, sigma0=1.0)
p = np.stack(es.ask(100000))
p.mean(axis=0)
```
The output (the population average) is roughly equivalent to my initial mean `x0`:
```python
array([0.02886446, 0.04429461, 0.05468557, 0.49841971, 2.00095892, 2.99696091])
``` 
This is fine and what I would have expected.

Now the same thing but with bounds:
```python
x0 = np.asarray(
    [0.03, 0.04, 0.05, 0.5, 2.0, 3.0]
)
bounds = [
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [1.0, 4.0, 6.0, 1.0, 4.0, 6.0]
]
es = cma.CMAEvolutionStrategy(x0=x0, sigma0=1.0, inopts={"bounds": bounds})
p = np.stack(es.ask(100000))
p.mean(axis=0)
```
Now the output is:
```python
array([0.22634681, 0.75225151, 0.75410253, 0.50207487, 2.00931669, 2.99793257])
```
And that is the output which I don't understand, because it doesn't seem to be centred around my initial mean anymore.
Any idea what I might have done wrong?

P.S: Im using pycma version 3.3.0

**Comment by nikohansen** [comment]
The bound is implemented by a non-linear transformation which biases the samples close to the bound towards the center, see https://github.com/CMA-ES/pycma/blob/d3de870a42e130d9373d1ab7efbbc35631024cfe/cma/transformations.py#L184

Think about it: when we initialize the value directly on the bound, it _must_ be biased towards the center if _any_ variation is produced, because any variation in the other direction beyond the bound is not allowed.

**Comment by david-woelfle** [comment]
Thank you @nikohansen for the super quick response! I have thought about your point and I think I have found the source of my confusion. Could you just shortly confirm or correct my assumption below?

I think it is that CMA is sampling a Gaussian distribution but in the transformed space of the optimizer. As the transformation is non-linear the samples will not be Gaussian distributed in solution space and hence the empiric mean of the data is not centered around my initial solution `x0` as I expected above. However, we can see that pycma does the right thing if we eliminate the influence of the transformation function by sampling very closely around the mean:
```
import cma
import numpy as np

x0 = np.asarray(
    [0.03, 0.04, 0.05, 0.5, 2.0, 3.0]
)
bounds = [
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [1.0, 4.0, 6.0, 1.0, 4.0, 6.0]
]
es = cma.CMAEvolutionStrategy(x0=x0, sigma0=0.0000001, inopts={"bounds": bounds})
p = np.stack(es.ask(10000))
print(p.mean(axis=0))
```
Which returns:
```
[0.03 0.04 0.05 0.5  2.   3.  ]
```

**Comment by david-woelfle** [comment]
Thank you once more for your time!
