### ISSUE TITLE
if 1 < 3

### ISSUE THREAD

**Issue by mjvanderboon** [CMA-ES/pycma#239]
Hi,

Thanks for writing such a great tool.

In the source code, I find a lot of redundant if statements such as `if 1 < 3` or `11 < 3`. These statements occur a total of 118 times in the code base. What is the reason for this? Is it legacy that could be removed in a PR?

**Comment by nikohansen** [comment]
It allows to switch on/off parts of the code with the least number of keystrokes, namely one, and without code checkers complaining.
