### ISSUE TITLE
What do the UserWarnings mean?

### ISSUE THREAD

**Issue by de-ranit** [CMA-ES/pycma#248]
Hi,

Thank you very much for this Python package of CMA-ES.

I am not very familiar with CMA-ES code inside-out. But with the help of tutorials, I can use CMA-ES and it works pretty well for my use case. 

But I get the following warning message. I would really appreciate it if you could provide me with some hints about it.
```
/path/to/miniconda3/envs/my_env/lib/python3.10/site-packages/cma/evolution_strategy.py:1901: UserWarning: Sampling standard deviation i=4 at iteration 0 change by 0.08771832359215946 to stds[4]=0.04385964912280704
  warnings.warn("Sampling standard deviation i={} at iteration {}"
```

Where can I learn more about the warning messages of CMA-ES or get an idea about how to fix it (or maybe can safely ignore it)?

Thanks and regards,
Ranit

**Comment by nikohansen** [comment]
It is (generally) useful to give the calling sequence and parameters and options used when asking a question about the output. The above warning comes most likely from the discrepancy between the different between upper and lower bound of the fifth variable and a much larger (about tenfold) standard deviation given as input (`sigma0`). Sampling far beyond the bound(s) makes little sense, hence the code is correcting this input.

You may want to check out the bounds and rescaling section of [this notebook](https://github.com/CMA-ES/pycma/blob/development/notebooks/notebook-usecases-basics.ipynb) and/or [these practical hints](https://cma-es.github.io/cmaes_sourcecode_page.html#practical).

**Comment by de-ranit** [comment]
Thanks for the suggestions.

Sorry, I didn't include the call sequence and options. You are correct that my 5th parameter has a smaller range. But other parameters have a bigger range.

I am optimizing a function with 18 parameters. The call sequence is as follows.
```
import cma

def cost_func(param_vector):
        # do calculations
        return cost_value

options = {'bounds': [[0.0, 0.5, 0.5, 0.2, 0.8947368421052632, 0.0, 0.05, 0.0, 0.002, 0.038526039943027696, 0.4642503980947164, 0.01, 0.002, 0.0, 0.0, 0.0, 0.0, 0.0], 
[10.0, 3.5, 10.0, 200.0, 1.0263157894736843, 25.0, 2.0, 25.0, 2.0, 3.8140779543597416, 2.785502388568298, 10.0, 2.0, 4.166666666666667, 4.0, 3.3333333333333335, 6.818181818181818, 3.1034482758620694]], 
'maxiter': 500, 
'maxfevals': 50000, 
'popsize': 1000, 
'popsize_factor': 1, 
'tolx': 1e-06, 
'tolfun': 1e-06}

cma_es = cma.CMAEvolutionStrategy([1.0]*18, 0.5, options)
res = cma_es.optimize(cost_func)
```

**Comment by nikohansen** [comment]
I am not sure the argument
```python
zero=[-(lb/ub) for...
```
is correct for parameters with nonzero lower bound, I think it should read ``-lb/(ub-lb) for ...``?

This is why the development branch now implements a simpler way to pass the actual lower values like
```python
lower=options['bounds'][0]
```
However this would require for the time being to install the `cma` package like

```
pip install git+https://github.com/CMA-ES/pycma.git@development 
```

**Comment by de-ranit** [comment]
Thank you so much for checking it and suggesting the correction. The new `cma.ScaleCoordinates` seems very convenient. 

Does pycma have any function to convert back the `xbest` or `fbest` values (which will be between 0 to 1) in `res` dictionary to the actual parameter value (between the actual parameter range)?

I am currently using v3.3.0. Is there any significant difference between the v3.3.0 and the current development version? If not, then I will probably switch to the development version, or else I can correct my code as suggested by you.

**Comment by nikohansen** [comment]
> Can it handle a parameter bound between negative lower bound to positive upper bound (for e.g., -5 to 30)?

Yes.

> Does pycma have any function to convert back the xbest or fbest values (which will be between 0 to 1) in res dictionary to the actual parameter value (between the actual parameter range) or x_actual = multipliers * x_scaled + lower work for both zero and non-zero values of lower bound?

The `ScaleCoordinates` class has an `inverse` method which should give the desired solution when applied to `xbest` or `xfavorite` like
```python
cost_func2.inverse(cma_es.result.xfavorite)
```
Just a caveat, `cma_es.mean` is not necessarily in-bounds (it's a "genotype" solution), `xfavorite` is (internally) computed as ``es.result.xfavorite == es.gp.pheno(es.mean, into_bounds=es.boundary_handler.repair)``.

> I am currently using v3.3.0. Is there any significant difference between the v3.3.0 and the current development version?

There is no difference in the core functionalities.

**Comment by de-ranit** [comment]
Thank you so much for the clarifications.

> The `ScaleCoordinates` class has an `inverse` method which should give the desired solution when applied to `xbest` or `xfavorite` like
`cost_func2.inverse(cma_es.result.xfavorite)`

The following gives me `True` and it seems the actual parameter values are `multipliers * (xbest - zeros)`.
```
multipliers = [ub - lb for ub, lb in zip(options['bounds'][1], options['bounds'][0])]
zeros = [-lb/(ub-lb) for ub, lb in zip(options['bounds'][1], options['bounds'][0])]

cost_func(multipliers * (xbest - zeros)) == cost_func2(xbest)
```

So, I thought `multipliers * (xbest - zeros)` should be the same as `cost_func2.inverse(xbest)`. But in my case, they are not the same. So, I am a bit confused what's the correct way to get actual values of `xbest` (`multipliers * (xbest - zeros)` or `cost_func2.inverse(xbest)`).

**Comment by nikohansen** [comment]
> So, I thought multipliers * (xbest - zeros) should be the same as cost_func2.inverse(xbest). 

It seems to me that `multipliers * (xbest - zeros)` should be the same as `cost_func2.transform(xbest)` and that's indeed what you want, my mistake.

**Comment by de-ranit** [comment]
Perfect, now I can get the actual parameter values. Thank you so much.
