### ISSUE TITLE
VD-CMA-ES test

### ISSUE THREAD

**Issue by nikohansen** [CMA-ES/pycma#25]
The VD-CMA-ES test [here in `test.py`](https://github.com/CMA-ES/pycma/blob/master/cma/test.py#L249) *sometimes* fails. The outcome remains stochastic even when `np.random.seed` is set in advance and the rotation of the cigar function is omitted.

**Comment by youheiakimoto** [comment]
I could have not reproduced the failure. No run out of 100 independent trial exceeded 8000 evaluations (a few time exeeded 7000, but mostly about 6000). It is not fully related, but even cma also works stochastically even if I call np.random.seed.

**Comment by nikohansen** [comment]
After providing `cma.fitness_transformations.Rotated` with a `seed` argument, this issue is fixed.
