### ISSUE TITLE
What is the point of calculating 1^2 in recombination_weights.py?

### ISSUE THREAD

**Issue by Jark5455** [CMA-ES/pycma#250]
Hello,

I noticed that in the recombination_weights.py file, at line [237](https://github.com/CMA-ES/pycma/blob/3ab636c2adf965a152d594fb93ac9c297b4b0b65/cma/recombination_weights.py#L237) the code calculates the value of 1 squared. Is there a reason for this? Will it not just get optimized out by the interpreter?

**Comment by nikohansen** [comment]
The reason is to remind (me) why we see the one in the nominator of this expression: it comes from $(\sum_i |w_i|)^2$ which needs to be one for this code line to be correct.

**Comment by Jark5455** [comment]
:thumbsup:
