### ISSUE TITLE
Step size

### ISSUE THREAD

**Issue by Jcee52** [CMA-ES/pycma#252]
Hi, I am wondering about the parameter setting for the step size. When the search space is bounded to [0,1] and adaptive step size is not considered, what step size is suitable? 0.1 or 0.3 or 0.5?

**Comment by nikohansen** [comment]
This crucially depends on the objective of the experiment and the available budget / iterations the algorithm is supposed to run.

When the objective is to find the best possible solution (locally or globally) in the shortest amount of time (the standard objective, so to speak), a non-adaptive step-size seems generally not advisable.
