### ISSUE TITLE
doctest of purecma

### ISSUE THREAD

**Issue by nikohansen** [CMA-ES/pycma#26]
When given as a stand alone file, 

```import purecma
purecma.test()
```
does not execute any tests. Furthermore, 
```
doctest.testmod(purecma)
```
fails, because the tests contain `import cma.purecma`.

**Comment by nikohansen** [comment]
`purecma.test()` from within the Python shell still doesn't execute any tests.

**Comment by nikohansen** [comment]
@truenicoco , would you be willing to make a pull request for the test fix (without the additional changes)? Otherwise, is it OK if I use your idea to make the necessary modifications on my own?

**Comment by truenicoco** [comment]
I'm not sure what happened there. I forked just to change a few `print()`s to `logging.debug()`s for my own use, but I'm not the author of any other modifications. I'm still learning GIT…

**Comment by nikohansen** [comment]
OK, I see, my mistake, I was commenting on my own commits ;-)

**Comment by nikohansen** [comment]
``python purecma.py`` works for executing the test, which seems good enough for the time being.
