### ISSUE TITLE
Passed parameter changes its value with BoundPenalty and BoundTransform

### ISSUE THREAD

**Issue by brockho** [CMA-ES/pycma#271]
Is there a good reason why the `bounds` parameter, when set via `BoundPenalty` changes its value? When calling
```python
import cma
mybounds = [-4, 4]
print(mybounds)
bp = cma.BoundPenalty(bounds=mybounds)
print(mybounds)   
print('---')
mybounds = [-4, 4]
print(mybounds)   
bp = cma.BoundPenalty(bounds=[b for b in mybounds])
print(mybounds)
```
for example, I get
```
[-4, 4]
[[-4], [4]]
---
[-4, 4]
[-4, 4]
```
The same happens by the way when `BoundPenalty` is replaced with `BoundTransform`.

**Comment by nikohansen** [comment]
The "reason" is that the code doesn't make a copy of the input argument as [documented here](https://github.com/CMA-ES/pycma/blob/384e8ce2803c53508e8d90f1c173c3bdd8832686/cma/constraints_handler.py#L24) and adapts the format in [this line](https://github.com/CMA-ES/pycma/blob/384e8ce2803c53508e8d90f1c173c3bdd8832686/cma/constraints_handler.py#L46) to some standard it relies upon later.

However, I don't see a good reason why [this line](https://github.com/CMA-ES/pycma/blob/384e8ce2803c53508e8d90f1c173c3bdd8832686/cma/constraints_handler.py#L41) should not be preceded by making a copy like

```python
            bounds = list(bounds)
            l = [None, None]  # figure out lengths
```
which would make the code also more robust in case `bounds` was a `tuple`.

**Comment by nikohansen** [comment]
This will be fixed in an upcoming release.
