### ISSUE TITLE
Inconsistent use of np.random.seed

### ISSUE THREAD

**Issue by youheiakimoto** [CMA-ES/pycma#28]
Both of `ConstRandnShift` class and `Rotation` class call `np.random.seed`. If seed is not given in the constructors,  the former doesn't call `np.random.seed`, but the latter calls it without an argument, which sets the seed using `/dev/urandom`, therefore we loose the full control of the random numbers. For a bug fixing, I prefer to have full control of random numbers. It is easy to correct, but I am not sure if it is a feature or a bug.

**Comment by nikohansen** [comment]
To my understanding of the code, we still keep control in both cases _from the outside_. That is, there is no arbitrary reset of the seed. The difference is that in case of the rotation `seed=None` means we will not be able to reproduce the rotation. The advantage is that we can set the `numpy` seed for the algorithm but get different rotations by default or if we want to (or fix the rotation if we want to by passing a seed). This is not the case for the shift: if we set the `numpy` seed, we do not produce a changing shift over different simulations ever.

We may contemplate over this, but to me it looks more like a feature than a bug. It suggests that for the shift the actual result is relevant and can be interpreted, while for the rotation it is not (which makes some sense to me). We can try to figure out an interface which provides both options in each transformation. 

BTW, the `fitness_transformation.Rotated` class now has a `seed` optional argument which is passed to the rotation and used in the tests of V(k)D-CMA-ES.

**Comment by nikohansen** [comment]
To elaborate on this, I see four reasonable behaviours for managing the random numbers seed and state, namely
* use time as seed and in the end reset to the state on input (as implemented in the `Rotation` class only)
* use a given input seed and in the end reset to the state on input (as implemented in both classes)
* use the current state and in the end reset to the state on input, i.e. the same sequence is produced twice, inside and outside
* use the current state and do not reset in the end, i.e. advance the state (as implemented in the shift class only)

**Comment by youheiakimoto** [comment]
Thank you very much for the comments. I understand the points. I was misunderstanding the implementation of Rotation class.
