### ISSUE TITLE
Optimizing a 7-parameter black-box function

### ISSUE THREAD

**Issue by revanth-s** [CMA-ES/pycma#282]
Hi,

I am working on optimizing a 7-parameter black-box function and have some questions that I would really appreciate if you could help me with. I have listed them below:

1. **Parameter Scaling**
   - My parameters have different upper and lower bounds, and initially, some of them were exponential. I converted the exponential parameters to linear by taking the logarithm and passed them to CMA-ES.
     ```python
     log_parameter_bounds = [
         (-15, -10),
         (-17, -10),
         (2, 3.5),
         (0, 5),
         (1.5, 3),
         (-12, -6),
         (-13, -7),
     ]
     ```
   - Is it generally recommended to scale these parameters before optimization, for example, using `StandardScaler()`?

2. **Population Size**
   - After browsing through the documentation and reading papers, I decided to use a population size (`popsize`) greater than the number of parameters, and hence I had chosen `popsize = 8`.
   - What should the ideal value of `popsize` be?

3. **Parallel Population Search**
   - From my understanding, each `popsize` searches over a different area (independent from each other). Can each population search be performed in a separate thread in parallel using the `multiprocessing` python module?

4. **Relationship between `popsize` and `sigma0`**
   - I have noticed that increasing `popsize` also requires me to lower `sigma0` for my 7-parameter function to avoid crashing.
   - Is there a relationship between `popsize` and `sigma0`?

5. **Finding Multiple Local Minima**
   - My 7-parameter function has multiple local minima, and I want to find as many of these minima as possible.
   - Therefore, I want to restart CMA every time the algorithm is stuck on a minimum, but I have been finding it hard to find the right termination conditions to use to stop and restart the algorithm.
   - I tried using `tolupsigma`, but it never terminated optimization except when set to 1. When set to 1, the algorithm was terminated within 2-3 iterations.
   - Currently, I am using `tolstagnation = 2` and still facing the same problem.

Thank you in advance for your assistance.

**Comment by nikohansen** [comment]
re. 1: maybe have a look at these [practical hints](https://cma-es.github.io/cmaes_sourcecode_page.html#practical)
re. 2: if you don't know, use the default and increase if there is time left (IPOP-CMA-ES, so to speak). 
re. 3: not sure about the correctness of the statement, but this may be related: https://github.com/CMA-ES/pycma/issues/276
re. 4: maybe have a look again at the [practical hints](https://cma-es.github.io/cmaes_sourcecode_page.html#practical), and Fig.1 in [this reference](https://link.springer.com/chapter/10.1007/978-3-642-32937-1_30) suggests that this also entirely depends on the function to be optimized
re. 5: what about the defaults? Otherwise, the `'tol*'` options are the goto options to consider, see e.g. [here](https://github.com/CMA-ES/pycma/issues/171#issuecomment-853804743)

**Comment by revanth-s** [comment]
Thank you for your reply.

Questions 1 to 4 are answered satisfactorily for me. However, I believe I can provide more information regarding question 5.

5. When I utilized the default values for termination, the algorithm terminated with the condition `noeffectaxis=None` after approximately 1000 evaluations (125 iterations for a population size of 8). I am seeking a way for the algorithm to terminate much earlier. My objective is to run a maximum of 2400 evaluations.

**Comment by nikohansen** [comment]
You may want to use a larger [`'tolx'` or `'tolfun'`](https://github.com/CMA-ES/pycma/issues/171#issuecomment-853804743) (tolx is in essence the effective sigma, as also suggested above). Less flexible, you can define the maximum evaluations or iterations or use the `'ftarget'` to terminate when an f-value below ftarget is reached.

```python
import cma

cma.CMAOptions('max')
```
```python
{'maxfevals': 'inf  #v maximum number of function evaluations',
 'maxiter': '100 + 150 * (N+3)**2 [//](https://github.com/CMA-ES/pycma/issues/282) popsize**0.5  #v maximum number of iterations',
 'maxstd': 'None  #v maximal std (scalar or vector) in any coordinate direction',
 'maxstd_boundrange': '1/3  # maximal std relative to bound_range per coordinate, overruled by maxstd',
 'tolupsigma': '1e20  #v sigma/sigma0 > tolupsigma * max(eivenvals(C)**0.5) indicates "creeping behavior" with usually minor improvements',
 'verbose': '3  #v verbosity e.g. of initial/final message, -1 is very quiet, -9 maximally quiet, may not be fully implemented'}
```
