### ISSUE TITLE
Clarification requested re hsig adjustment in purecma.py

### ISSUE THREAD

**Issue by drallensmith** [CMA-ES/pycma#33]
https://github.com/CMA-ES/pycma/blob/0e4a1ba5291f983e21fdfb9ed4a06673122dd5ac/cma/purecma.py#L405

Part of the purpose of purecma.py is to help understand the algorithm. What is the purpose of the "<" in this line? Thanks!

**Comment by nikohansen** [comment]
I am not so sure I understand the question. It compares the size of the left term (which I believe is in expectation 1) with 2 + something and results in `True` or `False`.

**Comment by drallensmith** [comment]
I've put in a pull request with what I _think_ you (and the code) are saying is happening with hsig, although I still have a couple of questions if my interpretation is correct.
