### ISSUE TITLE
"if 11 < 3:"?

### ISSUE THREAD

**Issue by drallensmith** [CMA-ES/pycma#35]
https://github.com/CMA-ES/pycma/blob/0e4a1ba5291f983e21fdfb9ed4a06673122dd5ac/cma/purecma.py#L1211

Is this intended to comment out this section? If so, it could be a bit clearer...

**Comment by nikohansen** [comment]
It is the simplest (single key stroke) way I know of to in- and outcomment parts of the code on which code checkers do not complain. I am using it for years all over the place, find it very practical, and haven't found any better way to do it so far. If there are a better ways, I am eager to know about.

**Comment by drallensmith** [comment]
Got it. My confusion was because the code above was using the variable name `l`, which in many fonts looks very much like (or even identical to) the numeral one. As well as possibly changing the prior variable name, perhaps 22 < 3? As it was, I was looking around for an `ll` variable.

Part of my interest, incidentally, is from wanting to possibly incorporate CMA-ES into [NEAT-Python](https://github.com/CodeReclaimers/neat-python) - actually something I was considering even before I read of EANT2; purecma is of interest because:

- NEAT-Python has a policy of being functional (if not fast) with just the Python standard libraries (so a version of purecma would be ideal if it could take advantage of numpy.dual.eigh - which in turn takes advantage of scipy when available - but fall back on pure-python code when need be)
- Licensing differences. (BTW, thanks very much for making the code available in general, and purecma as public domain in particular!)

**Comment by nikohansen** [comment]
Do you have any insight into the difference between `scipy.linalg.decomp.eigh` and `numpy.linalg.linalg.eigh`?

**Comment by drallensmith** [comment]
Numpy does not absolutely require itself to be built with BLAS and LAPACK (it apparently has some non-optimized versions of the needed routines); scipy does, and is more likely to be installed with optimized versions such as ATLAS or OpenBLAS. (There is the admitted problem that Apple's optimized versions conflict with Python's multiprocessing module due to use of threads; installing and using ATLAS or OpenBLAS instead is therefore recommended.)
