### ISSUE TITLE
How to set bounds

### ISSUE THREAD

**Issue by Rogerjwhill** [CMA-ES/pycma#36]
Hi,

I can't work out how to set bounds for CMAESvolutionStrategy.
Could you explain?

Thank you

**Comment by nikohansen** [comment]
Did you already try this
```python
import cma
cma.CMAOptions('bound')
```
and follow the comment?

**Comment by Rogerjwhill** [comment]
I did but didn't seem to work. But I have worked it out now thank you.

Best,
Roger

On 21 Sep 2017, at 17:40, nikohansen <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you already try this

import cma
cma.CMAOptions('bound')

and follow the comment?
