### ISSUE TITLE
condition alleviation bug

### ISSUE THREAD

**Issue by nikohansen** [CMA-ES/pycma#37]
Shows up in particular when the condition is high and hence the smallest eigenvalue is increasing by orders of magnitude _and_ eigenvectors are not aligned in the coordinate system. The bug shows up for both, alleviation in coordinates and resetting C=I. ``self.alleviate_conditioning_in_coordinates(1e2)`` was used in this example to see both in on run:

<img width="1286" alt="screen shot 2017-10-15 at 13 06 53" src="https://user-images.githubusercontent.com/7316439/31584201-f8f8cb30-b1a9-11e7-8ccc-a8cab5e721fe.png">

```python
import functools
import cma
f = functools.partial(cma.ff.elli, cond=1e28)
frot = cma.fitness_transformations.Rotated(f)
es = cma.fmin2(frot, [1] + 3 * [0], 0.1, {'tolconditioncov':False, 
                                  'seed': 4,
                                 })[1]
```

**Comment by nikohansen** [comment]
The suspicion that it may be related to how `ps` is treated within the transformation (or it's possible lack of invariance) seems not to be supported by the step-size behaviour.

**Comment by drallensmith** [comment]
Is accumulated roundoff error possibly related to this? I note some instances (outside of fitness functions) where sum (instead of np.sum or, for purecma.py, math.fsum) is being used. (Linear algebra is admittedly not my best area, by far.)

**Comment by nikohansen** [comment]
The culprit was setting genotype transformation, which was simply wrong when `sigma_vec` was not the identity.
