### ISSUE TITLE
negative impact of injection on performance

### ISSUE THREAD

**Issue by nikohansen** [CMA-ES/pycma#38]
A single injected solution should not have any relevant negative impact on performance, however we can see this:
<img width="1251" alt="screen shot 2017-10-16 at 21 34 30" src="https://user-images.githubusercontent.com/7316439/31631848-58173f40-b2bb-11e7-9360-c924034fa064.png">
roughly doubling the runtime by introducing a false short axis into C.

This suggests that the normalization of the injected point is not correct.

**Comment by nikohansen** [comment]
On a second thought, wrong normalization should have much much more pronounced effect. Indeed, it turns out the normalization is OK.

We probably see a legit effect on learning the distribution when injecting the same solution over and over again. The injected solution tends to be the worst (on the tablet function it tends to more often represent the short axis either) and hence affects "active" learning of the covariance matrix.

**Comment by drallensmith** [comment]
Any effect when "active" learning is turned off?

Thanks,

-Allen

**Comment by nikohansen** [comment]
The above is about 10% faster without "active" updates and about 15% faster without "active" updates and without injection.
