### ISSUE TITLE
CMAEvolutionStrategy.mean has invalid shape when some variables are fixed

### ISSUE THREAD

**Issue by FloopCZ** [CMA-ES/pycma#42]
`CMAEvolutionStrategy.mean` returns only free (e.g., the optimized) variables, when some variables are fixed using the `fixed_variables` options. The set of candidates returned by `.ask()` is shaped correctly, though.

**Comment by nikohansen** [comment]
This is rather a feature than a bug. All internal representations ignore the fixed variables, hence also the distribution mean.
```python
es.gp.pheno(es.mean)
```
is probably what you want. `es.gp` is the genotype-phenotype transformation.

**Comment by FloopCZ** [comment]
Thanks, your suggestion solves the problem. I was confused that I was getting a different vectors from `ask` and `mean`, since both these members are public, but using `gp` works fine. :+1:
