### ISSUE TITLE
Weird variance change with mirrors in high dimension

### ISSUE THREAD

**Issue by nikohansen** [CMA-ES/pycma#43]
```python
es = cma.fmin2(cma.ff.elli, 360 * [1], 1,
    {'CMA_diagonal':True,
    # 'CMA_mirrormethod': 0,
    'CMA_mirrors':True,
    # 'AdaptSigma': cma.sigma_adaptation.CMAAdaptSigmaCSA,
    'popsize': 160,
    'maxiter': 1200,
    'ftarget': 1e-9,
})[1]
cma.plot()
```
<img width="606" alt="screen shot 2017-11-18 at 19 25 33" src="https://user-images.githubusercontent.com/7316439/32983541-861b22b8-cc96-11e7-8ba8-3516dc763cc3.png">
<img width="539" alt="screen shot 2017-11-18 at 19 26 36" src="https://user-images.githubusercontent.com/7316439/32983542-8c92f17a-cc96-11e7-9116-8c245c6a74c9.png">
<img width="541" alt="screen shot 2017-11-18 at 19 26 24" src="https://user-images.githubusercontent.com/7316439/32983544-9175ff48-cc96-11e7-9742-0453e64e06ac.png">

We see a change of a coordinate-wise standard deviation by a factor of up to almost 3000 in a single iteration. This happens only with selective delayed mirrors and diagonal and active update and large population size and large dimension but irrespectively of the step-size adaptation method.

**Comment by youheiakimoto** [comment]
If I replace log(2) with 0.5 in the the following part:
https://github.com/CMA-ES/pycma/blob/1f15e1e13d36be48dfe6e847cb8bdc23725271bb/cma/transformations.py#L641
I get a more reliable result:
![image](https://user-images.githubusercontent.com/21190193/33070512-86b4d4ca-ceb8-11e7-8cd5-8ba292278241.png)
Still, there are some components that decreases rapidly.

**Comment by nikohansen** [comment]
Just another typical case:

![screen shot 2017-11-21 at 12 00 04](https://user-images.githubusercontent.com/7316439/33074039-115658c2-cec5-11e7-8437-a8a9228fca04.png)

**Comment by nikohansen** [comment]
At least in part, the problem is that a mirror can be re-injected again, and again... This has been provisionally fixed.

**Comment by nikohansen** [comment]
By now, mirrors are not anymore used to update the covariance matrix with negative weights.
