### ISSUE TITLE
boundary_handler error

### ISSUE THREAD

**Issue by lucianopaz** [CMA-ES/pycma#51]
When calling fmin for multidimensional functions with non-None bounds, where the bounds are provided as numpy arrays, line 113 from cma/constraints_handler.py throws the following error:

    File "/usr/local/lib/python3.5/dist-packages/cma/evolution_strategy.py", line 3822, in fmin
      es = cma.CMAEvolutionStrategy(x0, sigma_factor * sigma0, opts)
    File "/usr/local/lib/python3.5/dist-packages/cma/evolution_strategy.py", line 1377, in __init__
      if not self.boundary_handler.has_bounds():
    File "/usr/local/lib/python3.5/dist-packages/cma/constraints_handler.py", line 114, in has_bounds
      if bounds in (None, [None, None]):
    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by lucianopaz** [comment]
I was about to submit a pull request to solve this error, and I saw that latest development code already solved it. Sorry for the inconvenience. You can close this issue without any problem.

**Comment by nikohansen** [comment]
Thanks for the report. I guess I should also update the distribution in `pypi` timely.
