### ISSUE TITLE
std explode to very high values with VkD

### ISSUE THREAD

**Issue by adder** [CMA-ES/pycma#59]
Hey,

I'm testing CMA-ES on a high input space( >1000 parpameters)
When I run the regular CMA sampler my std stays more or less the same over multiple iterations. ( no decrease)
When I try the VdK sampler, the std increases exponentionally.
I tried to set the `maxstd` option to control this but it does not seem to work ( std still increases above max threshold).
I set the population to 100 and all other settings are default.
The fitness with both the CMA and VdK sample seems to plateau.

You have any idea what is going on? Is there a way to control the max std so it stays on sane levels?

Best regards

**Comment by nikohansen** [comment]
Could you post a plot of the observations (using `cma.plot`)?
