### ISSUE TITLE
create an official conda build

### ISSUE THREAD

**Issue by nikohansen** [CMA-ES/pycma#63]
see https://github.com/CMA-ES/pycma/pull/62, `conda-build -q tools/conda.recipe` is the command to go.

**Comment by nikohansen** [comment]
To install from anaconda ``conda install -c cma-es cma`` should do now.

**Comment by rpanai** [comment]
> To install from anaconda `conda install -c cma-es cma` should do now (`-c` = `--channel`)

I actually build a recipe for `conda-forge` [cma](https://anaconda.org/conda-forge/cma) for some reasons I'm investigating didn't automatically update (see [auto PR](https://github.com/conda-forge/cma-feedstock/pull/4)) but I'm now working on it .

**Comment by rpanai** [comment]
Done [PR](https://github.com/conda-forge/cma-feedstock/pull/5)
