### ISSUE TITLE
useless ask()

### ISSUE THREAD

**Issue by TMorzadec** [CMA-ES/pycma#65]
I am trying to use the cma-es module, by a specific way in which I give the first generation. See the following code:

dimension = ((number_of_control_Points_in_body - 3) * 2 + number_of_holes*(5 + number_of_control_Points_in_holes*2))

    es = cma.CMAEvolutionStrategy(dimension * [0.25], 0.3, { 'maxiter' : str(max_iter), 'popsize' : str(pop_size), 'bounds': [-0.2, 1.0]})
    

    es.ask()

    [X, fit] = generate_pop_init(pop_size, 5, 5, disjoint_holes = False, Symmetry = False)

    es.tell(X, fit)

    
    while not es.stop():

        X, fit = es.ask_and_eval(objective_func)
        es.tell(X, fit)
        es.logger.add()
        es.logger.disp([-1])
        es.disp()

    es.logger.disp_header()
    es.result_pretty()
    es.logger.plot()
    cma.s.figshow()
    print(es.result[1])
    xbest, fbest = es.result[0], es.result[1]

The first es.ask(), after es = cma.CMAEvolutionStrategy(...) is totally useless since I then give the first generation with a function. However, if I don't put it, I have the following errror:

File "CMAES_patte.py", line 99, in <module>
    es.tell(X, fit)
  File "/usr/local/lib/python2.7/dist-packages/cma/evolution_strategy.py", line 2379, in tell
    raise RuntimeError('tell should only be called once per iteration')
RuntimeError: tell should only be called once per iteration

Besides, I have not any plot, whereas I copy/paste the online examples, and I don't understand why.

**Comment by nikohansen** [comment]
The implementation does in general not support to use a population which is not generated by `ask`. The result could be completely unpredictable. I can't see what you are trying to achieve. After `tell` is called, there is no population anymore in the algorithm, so you can just give the weighted mean of the initial population from `generate_pop_init` as initial point. Specifically, 

```python
es.mean = dot(es.sp.weights.positive_weights, 
    [X[i] for i in np.argsort(fit)][:es.sp.mu]).T
```
should replace the first `ask` and `tell`. But then, this could also just be used as first argument to `CMAEvolutionStrategy`.

Regarding the failing plots, it is most likely a `matplotlib` problem. You need to give more information. Which operating system, which Python version, which environment/Python shell are you using, what happens if you type
```python
%pylab
plot([1,2,3])
```

**Comment by TMorzadec** [comment]
Hello, 

Thank you very much for your answer. 

Maybe if I give more information it will be more clear. 

I would like to optimize the mechanical behavior of soft shapes with a hole. The evaluation of the shape is done by a mechanical simulation (see mecanic.png). The simulation is quite long, it can take around 5 min for a "generic" shape, and 20 min for an "eccentric" one. 

I parametrize the shapes with left and right thicknesses around the y-axis (see figures 1-2-3, one parameter per horizontal segment). 

If I generate the shape randomly (with bounds) with a few parameters, I get figure 1. If I generate the shape randomly with a lot of parameters, I get figure 2, which is very long to evaluate. Hence, I have a technique to generate shapes with many parameters, see figure 3. 

If I give a "quite" good individual as first parameter in cma.CMAEvolutionStrategy(), for example in the following code 

"""""""""""""""""""""""""""" 

X = generate_n_indiviudal(n = 1, 5, 5, disjoint_holes = False, Symmetry = True)[0][0] 

es = cma.CMAEvolutionStrategy(X, 0.2, { 'maxiter' : str(max_iter), 'popsize' : str(pop_size), 'bounds': [-0.2, 1.0]}) 

index = 0 
while not es.stop(): 

X, fit = es.ask_and_eval(objective_func) 
es.tell(X, fit) 
print("round " + str(index)) 
index+=1 

es.logger.add() 
es.logger.disp([-1]) 
es.disp() 

es.logger.disp_header() 
es.result_pretty() 
es.logger.plot() 
cma.s.figshow() 
print(es.result[1]) 
xbest, fbest = es.result[0], es.result[1] 

""""""""""""""""" 
Firstly, I need a method to detect and reject "bad individual" before simulation, to gain time. 
It appears that the es.ask_and_eval() method cannot find a non rejected shape even after 1000 trials (for dimension space 38), and it takes around 50 trials to get a non rejected shape (for dimension space 22). And the shape it gets is quite "eccentric", or 
quite thick, and any way quite long to simulate (figure 4). Consequently, the algorithm is very long to start 

That why I wanted to help the algorithm giving it a first population of "not so long to evaluate" individuals 

That is why I use the following code: 

""""""""""""""" 
es = cma.CMAEvolutionStrategy(dimension * [0.25], 0.2, { 'maxiter' : str(max_iter), 'popsize' : str(pop_size), 'bounds': [-0.2, 1.0]}) 
es.ask() 

[X, fit] = generate_pop_init(pop_size, 5, 5, disjoint_holes = False, Symmetry = False) 

es.tell(X, fit) 

index = 0 
while not es.stop(): 

X, fit = es.ask_and_eval(objective_func) 
es.tell(X, fit) 
print("\n\n\n"+"round " + str(index)) 
index+=1 

es.logger.add() 
es.logger.disp([-1]) 
es.disp() 

es.logger.disp_header() 
es.result_pretty() 
es.logger.plot() 
cma.s.figshow() 
print(es.result[1]) 
xbest, fbest = es.result[0], es.result[1] 

""""""""" 

To initialize the first generation in a "fast to evaluate" maner 

It appears that, except for this ask() method I have to call for nothing, and maybe um predictable behaviors, it globally works, (at least it runs). 

But I am gonna try just to give a X0 parameter, and I will see (first code) 

For the plot, eventually it works if I call it from another shell, 

Thank you very much for your help, 

Sincerely yours, 

Thomas

**Comment by nikohansen** [comment]
> For the plot, eventually it works if I call it from another shell,

right, a plot may only appear after the code has finished running, even when `show()` has been called.

**Comment by nikohansen** [comment]
> I need a method to detect and reject "bad individual" before simulation, to gain time.

this will often lead into the situation that virtually no individual is accepted. As a simple alternative compute the distance to the best feasible point plus some offset as surrogate fitness. Even this might not work. It is non-trivial to handle constraints in general, see also [here](http://cma.gforge.inria.fr/cmaes_sourcecode_page.html#boundaries) for a little more information.

**Comment by nikohansen** [comment]
> That why I wanted to help the algorithm giving it a first population of "not so long to evaluate" individuals

Chose `x0` feasible and `sigma0` to be sufficiently small.

**Comment by nikohansen** [comment]
> If I generate the shape randomly (with bounds) with a few parameters, I get figure 1. If I generate the shape randomly with a lot of parameters, I get figure 2, which is very long to evaluate. Hence, I have a technique to generate shapes with many parameters, see figure 3.

I don't know which figures you are referring to.

**Comment by TMorzadec** [comment]
Thank you for your answer! 

Actually, I have put the method to detect and reject "bad individuals" into the eval function. If the individual is detected as "bad" it returns "NaN", without simulation 

It is not so bad, I think, like this. At least, in small dimension (< 20), it runs, with a few trials before getting a "evaluable" individual. 

I am currently testing both methods (give a single "good" individual as input, or give the first generation). It appears that they are quite as fast, (or quite as slow...), except for the first generation that is slower in the first case, of course 

Here is my plan. 

- Launch the algorithm for a dozen simulations with dimension = 14, sigma0 = 0.5 

- get the best individual 

- add some degree of freedom, without changing the shape (with an appropriate method) 

-launch again for a dozen simulations with dimension = 20, sigma0 = 0.25 

and so on, 

I will let you know if you are interested, 

Thank you very much, 

Sincerely yours, 

Thomas

**Comment by TMorzadec** [comment]
> De: "nikohansen" <notifications@github.com>
> À: "CMA-ES" <pycma@noreply.github.com>
> Cc: "TMorzadec" <thomas.morzadec@inria.fr>, "Author" <author@noreply.github.com>
> Envoyé: Mardi 24 Avril 2018 14:47:08
> Objet: Re: [CMA-ES/pycma] useless ask() (#65)

>> For the plot, eventually it works if I call it from another shell,
> right, a plot may only appear after the code has finished running, even when
> show() has been called.
What if I launch two or more cma-es algorithms simultaneously?

**Comment by nikohansen** [comment]
You only have to be careful where the logger is writing its data. If you have two instances in the same folder, they will garble each others logger output data. Assigning ``es.logger.default_prefix`` to a different value for each `es` instance should do the trick.

**Comment by TMorzadec** [comment]
Eventually, I have put files in separated folders, it is easier. 

For further improvement, I would like to use multiprocessing. In the doc, it is written: 

(however 
multiprocessing seems not always reliable) 

Why? 

May I use ask_and_eval method with multiprocessing? I like this method because it generate a new individual if the first attempt return NaN 

I also wanted to ask: I am working on optimization of shapes. I am interested in discovering new methods for optimization. 

I will be in Palaiseau the 14th, 17th and 18th of May. 

If you are interested, and if you have time for it, could we meet for this occasion, please 

Thank you very much for your help, 

Sincerely yours, 

Thomas

**Comment by nikohansen** [comment]
> (however
> multiprocessing seems not always reliable)
> 
> Why?

I don't know. The comment may not be up to date.

You may want to look at this
https://github.com/CMA-ES/pycma/blob/721ef6bc94890556564cf575a5234deadf655e17/cma/fitness_transformations.py#L16-L17
and consider this caveat
https://github.com/CMA-ES/pycma/blob/721ef6bc94890556564cf575a5234deadf655e17/cma/fitness_transformations.py#L58-L59
My practical experience with this is quite limited.

**Comment by TMorzadec** [comment]
I have forgotten to ask? 

What is the licence on CMA-ES? May I use it freely? What if I publish an article about my work using it? 

Best, 

Thomas

**Comment by nikohansen** [comment]
> What is the licence on CMA-ES?

Please see the LICENCSE file [here](https://github.com/CMA-ES/pycma).
