### ISSUE TITLE
What kind of CMA-ES is implemented?

### ISSUE THREAD

**Issue by HarryWindsor** [CMA-ES/pycma#73]
While reading through papers, I realized there a lot of different types of CMA-ES.
What type of CMA-ES is implemented here? Are there multiple? Is it possible to change between them?

 - [CMA-ES with restarts](https://ieeexplore.ieee.org/document/6557593/)
 - [IPOP-CMA-ES](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.216.1537&rep=rep1&type=pdf)
 - [Active Covariance Matrix Adaptation for the (1+1)-CMA-ES](https://hal.archives-ouvertes.fr/hal-00503250/document)

**Comment by nikohansen** [comment]
The code is pretty rich in options. It supports however mainly non-elitist versions. Restarts can be done somewhat trivially by implementing a loop. The "natively" supported (B)IPOP versions do most likely not match the exact settings of the above mentioned reference.

**Comment by HarryWindsor** [comment]
When I understand it right, running 
```python
import cma
es = cma.CMAEvolutionStrategy(8 * [0], 0.5)
es.optimize(cma.ff.rosen)
es.result_pretty()
``` 
 will be (μ/μw, λ)-CMA-ES.

**Comment by nikohansen** [comment]
That is correct ;-)
