### ISSUE TITLE
Error with 'B is not orthogonal' specifically on IBM power8 architecture. 

### ISSUE THREAD

**Issue by zuoxingdong** [CMA-ES/pycma#75]
Suppose running the following code

```
import cma

es = cma.CMAEvolutionStrategy([3]*100, 0.5, {'popsize': 12})
for i in range(1000):
    x = es.ask()
    c = list(range(12))
    
    es.tell(x, c)
    
    print(f'Iteration {i}: es.result["xfavorite"]')
```
After some iterations, it shows the following error
```
B is not orthogonal

    318             print('B is not orthogonal')
    319             print(self.D)
--> 320             print(sum(self.B[:, 0:self.N - 1] * self.B[:, 1:], 0))
    321         # is O(N^3)
    322         # assert(sum(abs(self.C - np.dot(self.D * self.B,  self.B.T))) < N**2*1e-11)

AttributeError: 'GaussFullSampler' object has no attribute 'N'
```

This refers to the latest version 2.6.0. 

------------------Update--------------------------------

After more tests, it works perfectly with all other machines, but just except for IBM Power8 architecture. Quite interesting, I am thinking if it is possible to have something to do with MKL ? Because MKL only supports Intel chips, I installed magma instead.

**Comment by nikohansen** [comment]
Thanks for the report! I reckon this has to do with limited numerical precision of the architecture. As a quick fix setting
```
es.sm._assertions_quadratic = False
```
should do.

I will fix the bug of the missing `self.N` attribute.
