### ISSUE TITLE
Can fmin using EvalParallel?

### ISSUE THREAD

**Issue by LinXiyao** [CMA-ES/pycma#78]
How to do parallel evaluation in fmin function?  It seems that the feature has been removed.

**Comment by nikohansen** [comment]
Right, `cma.fmin` doesn't have this option. It is documented in `cma.fitness_transformations.EvalParallel` how to use this class.

**Comment by LinXiyao** [comment]
Thanks.

**Comment by JW-spec-tech** [comment]
Is there anyway to speed up cma.fmin? I'm curious as to why the EvalParallel was removed from fmin?

**Comment by nikohansen** [comment]
`cma.fmin` has the optional argument `parallel_objective` and I guess one could use a `cma.fitness_transformations.EvalParallel2` class instance for this argument.
