### ISSUE TITLE
How to define custom parameters of CMA-ES?

### ISSUE THREAD

**Issue by AptX395** [CMA-ES/pycma#79]
When I create a new object of `class CMAEvolutionStrategy`, how could I define custom parameters such as `sp.cc`, `sp.c1`, `sp.cmu`?

**Comment by nikohansen** [comment]
Sorry for the late reply. I am not sure where this is precisely heading, but `sp` is of type ``cma.evolution_strategy._CMAParameters``. You can set or change attributes of the parameters instances, like

```python
es = cma.CMAEvolutionStrategy(...)
es.sp.cc = 1/3
es.optimize(...)
```

**Comment by AptX395** [comment]
Thanks for your reply!



在 nikohansen <notifications@github.com>，2018年11月6日 01:56写道：

Sorry for the late reply. I am not sure where this is precisely heading, but sp is of type cma.evolution_strategy._CMAParameters. You can set or change attributes of the parameters instances, like

es = cma.CMAEvolutionStrategy(...)
es.sp.cc = 1/3
es.optimize(...)
