### ISSUE TITLE
How to define lower and upper bounds? Description of 'bounds' and 'transformation'?

### ISSUE THREAD

**Issue by mohagh453** [CMA-ES/pycma#80]
Hello, 

I really appreciate if you can tell me how i can input the lower and upper bound of my optimization parameters?
Also, I searched a lot, but I couldn't find the instruction about 'bounds' and 'transformation' in the option parameter.

Thanks in advance
Yours sincerely

**Comment by nikohansen** [comment]
```python
import cma
cma.s.pprint(cma.CMAOptions('bound'))

{'BoundaryHandler': 'BoundTransform  # or BoundPenalty, unused when ``bounds '
                    'in (None, [None, None])``',
 'bounds': '[None, None]  # lower (=bounds[0]) and upper domain boundaries, '
           'each a scalar or a list/vector'}
```
suggests `bounds` as `lower (=bounds[0]) and upper domain boundaries, each a scalar or a list/vector`.

That is the option
```python
{bounds: [-1, 1]}
```
would bound the domain between -1 and 1 for all variables.

**Comment by mohagh453** [comment]
Many thanks for your reply. I really appreciate if you please give me an example setting different boundaries for the each variable (e.g x1:[-1 1], x2:[10 20])

Is it going to be like: {bounds: [[-1,10],[1,20]}

Thanks in advance Your sincerely

**Comment by FCamborda** [comment]
Hi,
From 
> bounds must be None, empty, or a list of length 2 where each element may be a scalar, list, array, or None
means that for lower bounds a0 < x0 < b0 and a1 < x1 < b1 you can do something like
`import cma
es = cma.CMAEvolutionstrategy([5,5], 2, {'bounds':[[a0,a1], [b0,b1]]}
`
> (3_w,6)-aCMA-ES (mu_w=2.0,w_1=63%) in dimension 2 (seed=703058, Wed Nov  7 23:22:56 2018)

You can also specify the kind of BoundaryHandler you require by using 'BoundaryHandler':  and the respective value before 'bounds'. You can find more about that by calling help(cma.constraints_handler) on your python shell after having imported cma.

Generally, you should take a look at this:
http://cma.gforge.inria.fr/cmaes_sourcecode_page.html#practical

@nikohansen from the above link (on encoding of variables), what does "similar sensitivity" mean? For example, I have 3 components on a vector. One (x  coordinates) can range from 0 to 50, the other one(y) from 50 to 100, and a last one (orientation) lets say 0 to 360 degrees. Is sensitivity then related to my fitness function? I'm a complete newbie here, so I might be confusing the terms "where a variable 'lives'" and boundary constraints? And is this proper encoding necessary (as the covariance matrix starts as the identity?)
Beste Grüße

**Comment by mohagh453** [comment]
Thank you very much. I really appreciate it.

As a last question, is there any way for integer constraint? I have a graph, and for each edge, there should be {0,-1,1} (0= no edge, +1 or -1=unidirectional edge). I want to optimize the output by changing the graph structure and its weights.

I extremely appreciate if you please let me know if integer constraint and boundary option is available.
Yours sincerely

**Comment by nikohansen** [comment]
> from the above link (on encoding of variables), what does "similar sensitivity" mean? 

It refers to the effect on the objective function when single variables are changed by some given Delta. The stronger the effect of the change on the fitness, the more sensitive this variable is. Of course this depends on the position in search space, but it is still a useful notion.

> I might be confusing the terms "where a variable 'lives'" and boundary constraints?

To me these are the same.

**Comment by nikohansen** [comment]
> As a last question, is there any way for integer constraint? I have a graph, and for each edge, there should be {0,-1,1} (0= no edge, +1 or -1=unidirectional edge). I want to optimize the output by changing the graph structure and its weights.

This doesn't look like something CMA-ES would be the first choice to use for optimization. On the specific question, check out

```python
>>> import cma
>>> print(cma.CMAOptions('integer')
{'integer_variables': '[]  # index list, invokes basic integer handling: prevent std dev to become too small in the given variables'}
```
The solutions themselves are still vectors of floats, but the rounded or truncated values of their integer variables can be used as the integer value.
