### ISSUE TITLE
How does the plot function work ?

### ISSUE THREAD

**Issue by MoMe36** [CMA-ES/pycma#83]
Hi ! 

How does the plot function work ? When I call `plot`, the script writes some files on disk, but nothing is displayed. How can I read the `.dat` files ? 

Thanks

**Comment by nikohansen** [comment]
The function plots a figure like seen [here](https://github.com/CMA-ES/pycma/issues/43#issue-275099705) (it only writes data if downsampling is applied). A known problem is that the figure does not always show up in the foreground of the desktop/screen.
```python
from matplotlib import pyplot
pyplot.show()
```
usually solves this problem. Another known "problem" is that if `plot` is called in a Python script called from an OS shell, the figure closes when the script finishes.

**Comment by fooSynaptic** [comment]
> The function plots a figure like seen [here](https://github.com/CMA-ES/pycma/issues/43#issue-275099705) (it only writes data if downsampling is applied). A known problem is that the figure does not always show up in the foreground of the desktop/screen.
> 
> ```python
> from matplotlib import pyplot
> pyplot.show()
> ```
> 
> usually solves this problem. Another known "problem" is that if `plot` is called in a Python script called from an OS shell, the figure closes when the script finishes.

quite ambiguous for the "finish", when calling the plot.show() ， the python process will blocked.

In my pycma useage, the pyplot cannot show the images, just leave a new dir name "outmaes", how can i solve this problem?

**Comment by nikohansen** [comment]
What happens if you run in a Jupyter notebook

```python
%pylab nbagg
import cma
x, es = cma.fmin2(cma.ff.elli, 4 * [1], 1)
cma.plot()
```

**Comment by LiHongming666** [comment]
hello Nikohansen,
        the same issue is observed in my side, below is the result from the three lines you recommand.

import cma

x, es = cma.fmin2(cma.ff.elli, 4 * [1], 1)

cma.plot()

(4_w,8)-aCMA-ES (mu_w=2.6,w_1=52%) in dimension 4 (seed=792513, Fri Jan 15 16:51:07 2021)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1      8 4.669541555794340e+04 1.0e+00 1.24e+00  1e+00  1e+00 0:00.0
    2     16 4.275685420513510e+04 1.3e+00 1.38e+00  1e+00  2e+00 0:00.0
    3     24 1.695713260164658e+05 1.6e+00 1.21e+00  8e-01  1e+00 0:00.0
  100    800 1.228271134471422e-05 5.6e+02 2.97e-03  4e-06  2e-03 0:00.1
  182   1456 1.846711254664596e-15 9.6e+02 9.68e-07  4e-11  3e-08 0:00.2
termination on tolfun=1e-11 (Fri Jan 15 16:51:08 2021)
final/bestever f-value = 1.329685e-15 1.329685e-15
incumbent solution: [4.457678903721467e-09, -3.266317565909109e-09, -1.5433381123715628e-10, 2.1775241387242517e-12]
std deviation: [3.2928276076847273e-08, 3.402209311002443e-09, 2.685902877356119e-10, 3.5223729866295744e-11]

<cma.logger.CMADataLogger at 0x2a0809a5cc8>

**Comment by LiHongming666** [comment]
Hello Nikohansen,
the plot is fine after **input()** is added at last line

**Comment by Hamidkn** [comment]
When you are working in a Jupyter file: ```cma.plot()```, will work correctly, But if you are in a windows editor like VSCode, you must write a ```input()``` command. Finally, it works and it will show the figures. 
```
cma.plot()
input()
```
