### ISSUE TITLE
CMAAdaptSigmaCSA vs CMAAdaptSigmaTPA and mirroring errors

### ISSUE THREAD

**Issue by eyaler** [CMA-ES/pycma#84]
why for diagonal and n>299 we switch from CMAAdaptSigmaCSA to CMAAdaptSigmaTPA? is there any reference for this? if i am seeing CMAAdaptSigmaTPA apparent inconsistency with mirrored samples, is it a good idea to manually choose CMAAdaptSigmaCSA?

**Comment by nikohansen** [comment]
CSA performs bad if a larger number of variables is insensitive or even irrelevant, see e.g. [here](https://scholar.google.fr/scholar?cluster=4631712705240010321). This is (much?) more likely to happen in larger dimension. Moreover I feel that in general CSA may be slower to adapt an initially wrong step-size in larger dimension, but there is only sketchy empirical data and it depends on parameter settings which might not be well tuned for dimension >300 also in TPA (which doesn't help the end user, as the tuning is tedious and somewhat non-trivial, it only means there is some perspective for improvement in foreseeable future).

The mirroring option should be relatively unimportant in particular in large dimension.

I don't think there is anything particular wrong to use `CMAAdaptSigmaCSA` also in larger dimension given the function does not fall into the above category.
