### ISSUE TITLE
Newer cma versions import matplotlib somewhere, even when not plotting

### ISSUE THREAD

**Issue by MichaelClerx** [CMA-ES/pycma#91]
Having some issues testing libraries depending on `cma`, as it seems to load matplotlib - which prevents us from changing the matplotlib backend after importing `cma`

**Comment by MichaelClerx** [comment]
Think this is the culprit:

https://github.com/CMA-ES/pycma/blob/master/cma/optimization_tools.py#L5-L6

everywhere else it looks like matplotlib is only loaded inside functions

**Comment by nikohansen** [comment]
Thanks for the catch! Will be fixed with the next release.

**Comment by nikohansen** [comment]
Fixed with commit 10f1362d5dd355c63e8f67a519db75f9e9fa1c4b
