### ISSUE TITLE
Example for dummies

### ISSUE THREAD

**Issue by stabilus** [CMA-ES/pycma#92]
I have seen this phenomenon in many places in the field of data science. Either you know what everyone is talking about or you're so out that you don't know where to start. That's me...

I've somewhat managed to understand the ground rules that allow me to play with keras and tensorflow. But it took a lot of effort, simply because those who are IN, don't see the problems OUTers have: Wehre to start, how to implement, etc.

It would make it so much easier if anybody came up with an example an OUTsider can relate to and follow along: 

i.E. I am trying to create a model that learns weather patterns: Say:
- I have 1 weather station that grabs 4 features on an hourly interval (temperature, wind speed, wind direction, humidity, etc. and I have weather data reaching back 5 years.
- and I want to predict the temperature in 1h, 6h and 24h.

Now, let's assume I have installed CMA on my python environment. Now what?

- How do I provide my data? 
- How do I  prepare the model?
- How do I define batches (if the data is too big to load into memory)
- How do I define the fact that I am looking at sequences of data? 
- How do I define my rewards?
- What else needs to be done?
- How do I train the model now?
- How do I now predict the temperature, assuming I provide a sequence of the latest data?

A code along with this practical example would be really helpful.
Thanks all.

**Comment by nikohansen** [comment]
All good questions, though I am not sure that they are too much related to the py`cma` module itself.

Links that hint to the purpose of the `cma` module and to basic examples are provided in the [readme](https://github.com/CMA-ES/pycma/blob/master/README.md).
