### ISSUE TITLE
Parallel Evaluation on Windows

### ISSUE THREAD

**Issue by nickbeihoff** [CMA-ES/pycma#93]
I've been struggling to implement EvalParallel on Windows. The closest I've gotten is saving the parallel evaluation in a separate script (so my Jupyter notebook doesn't hang) and specifying `if __name__ == "__main__":` above the call to `EvalParallel`, like so:
```
def runparallel(i,input,workers):
	Input= input.tail(i).values
	Input[:,0] = 1
	start = [.5, 16, Input[:,1].max() + len(Input)/365/10]
	es = cma.CMAEvolutionStrategy(start, 1/365,
		{
		'verbose': -9,  
		'bounds': [[0.001,1, Input[:,1].max() + 1/365/2], 
		[1.999,20, Input[:,1].max() + len(Input)/365]]
		}
		)
	if __name__ ==  '__main__':
		with EvalParallel(workers) as eval_all:
			while not es.stop():
				X = es.ask()
				es.tell(X, eval_all(fun, X, tuple([Input])))
	return es
```
I have a test script, which compares the timing and output of `runparallel` against a serial function `runserial`. The serial procedure uses `cma.fmin`. The parallel procedure seems to be returning the start parameters.
![image](https://user-images.githubusercontent.com/22204375/62062124-04a89280-b1ee-11e9-9006-e9a90ba73d64.png)

**Comment by nikohansen** [comment]
It's a little hard to see how the above code produces the shown output. The code of `runparallel` seems to return a `cma.CMAEvolutionStrategy` instance, hence I don't see how it could return the shown array.

**Comment by nickbeihoff** [comment]
Sorry, I should have specified that the test script runs the following:
```
print('Running Serial')
t1 = time.time()
s = [rs.runserial(i,input) for i in ids]
print('Serial procedure took {} seconds.'.format(time.time()-t1))
pprint([s[i][0] for i in range(len(s))])

print('\n')
print('Running Parallel')
t2 = time.time()  
x = [rs.runparallel(i,input,14) for i in ids]
print('Parallel procedure took {} seconds.'.format(time.time()-t2))
pprint([x[i].result.xfavorite for i in range(len(x))])
```
Changing the last line to `pprint([x[i].result.xbest for i in range(len(x))])` outputs `[None]`

**Comment by nikohansen** [comment]
I suspect that `__name__ ==  '__main__' is False`, when `rs.runparallel` is called from the test script (where it is true). That would explain why the function delivers the initial solution.

It is still strange though how `result.xfavorite` can be `None`, as it is not even `None` right after initialization.
