### ISSUE TITLE
What should I do to limit the search space to [-1,1]？

### ISSUE THREAD

**Issue by shercklo** [CMA-ES/pycma#94]
Here are my core-codes:
```
self.strategy = cma.CMAEvolutionStrategy(x_start, 0.5)

 es = self.strategy

for count in range(budget):

    solutions = es.ask()

    es.tell(solutions, [cma.ff.rosen(s) for s in solutions])

    es.disp()
```

**Comment by nikohansen** [comment]
```python
self.strategy = cma.CMAEvolutionStrategy(x_start, 0.5, {'bounds': [-1, 1]})
```
should do.

Check out
```python
cma.CMAOptions('bound')
```

**Comment by shercklo** [comment]
Thanks a lot.

**Comment by unghee** [comment]
hello, can we set a different bounds for each dimension? for example, for 2dim case:
'''
def f(x, y):  # a 1-D function
    return x**2 + y**2

x0 = [[0.5],[0.8]]
strategy = cma.CMAEvolutionStrategy(x0, 0.5, {'bounds': [[-1, 1],[0,5]]})
'''

**Comment by nikohansen** [comment]
The lower bound of the second variable was set to 1 and the initial solution is 0.8, hence the error.

**Comment by unghee** [comment]
> 

It worked. Thank you for your help!
