### ISSUE TITLE
Optimization on Hartmann6D

### ISSUE THREAD

**Issue by a-z-e-r-i-l-a** [CMA-ES/pycma#97]
I wanted to ask if anyone has tried CMA on optimizing the Hartmann6D function. The bounds for this function are all defined between [0, 1] and I had an assertion error with these bounds unless I were to shrink the lower bounds slightly but even with that although the execution of optimization works, CMA doesn't explore for better optimums.

**Comment by nikohansen** [comment]
Care to point us to a Python implementation of the function in question?

**Comment by a-z-e-r-i-l-a** [comment]
> Care to point us to a Python implementation of the function in question?

I use this implementation:
https://automl.github.io/HPOlib2/stable/_modules/hpolib/benchmarks/synthetic_functions/hartmann6.html#Hartmann6

**Comment by a-z-e-r-i-l-a** [comment]
Yes sure, after installing their package it follows like this:

```
from hpolib.benchmarks.synthetic_functions.hartmann6 import Hartmann6
Hm = Hartmann6 ()
bounds = np.array (Hm.get_meta_information()['bounds'])

def function_to_optimize(x):
      output = Hm.objective_function(x)['function_value']
      return output

```

**Comment by nikohansen** [comment]
The solution I get "out-of-the-box" is ``[0.2016895 , 0.15001068, 0.47687397, 0.27533243, 0.31165161, 0.65730054]`` with a value of -3.322368011415494, which seems to be the optimum:
```python
import cma
xopt, es = cma.fmin2(function_to_optimize, 6 * [0.5], 0.3, {'bounds': [0, 1]}, restarts=3)

(4_w,9)-aCMA-ES (mu_w=2.8,w_1=49%) in dimension 6 (seed=172348, Mon Oct 14 17:30:52 2019)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1      9 -1.702384077256185e+00 1.0e+00 2.62e-01  2e-01  3e-01 0:00.0
    2     18 -1.417988733964211e+00 1.2e+00 2.52e-01  2e-01  3e-01 0:00.0
    3     27 -1.708383327367931e+00 1.4e+00 2.22e-01  2e-01  2e-01 0:00.0
  100    900 -3.203161389568209e+00 2.0e+01 1.07e-03  5e-05  8e-04 0:00.2
  176   1584 -3.203161918396207e+00 2.4e+01 1.09e-06  9e-09  2e-07 0:00.3
termination on tolfun=1e-11 (Mon Oct 14 17:30:52 2019)
final/bestever f-value = -3.203162e+00 -3.203162e+00
incumbent solution: [0.4046531251150994, 0.8824449070637312, 0.8461016813711737, 0.5739896872531729, 0.13892647881619735, 0.03849590413745968]
std deviation: [8.606046904534326e-09, 1.2555951179350746e-08, 1.775174975823382e-07, 1.5090540651590714e-08, 1.118574086988012e-07, 1.2967933382492991e-08]
(9_w,18)-aCMA-ES (mu_w=5.4,w_1=30%) in dimension 6 (seed=172349, Mon Oct 14 17:30:52 2019)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1   1603 -1.328314818324115e+00 1.0e+00 3.28e-01  3e-01  3e-01 0:00.0
    2   1621 -2.177371180452625e+00 1.4e+00 3.46e-01  3e-01  4e-01 0:00.0
    3   1639 -2.605976971808942e+00 1.5e+00 3.23e-01  3e-01  3e-01 0:00.0
  100   3385 -3.203161918394886e+00 2.6e+01 2.01e-05  9e-08  2e-06 0:00.3
  113   3619 -3.203161918396149e+00 1.9e+01 7.83e-06  3e-08  4e-07 0:00.4
termination on tolfun=1e-11 after 1 restart (Mon Oct 14 17:30:53 2019)
final/bestever f-value = -3.203162e+00 -3.203162e+00
incumbent solution: [0.404653123210907, 0.8824449356219095, 0.8461018609408707, 0.5739897040923728, 0.1389265796306935, 0.038495892381848064]
std deviation: [2.5881260721241814e-08, 3.4281634741738055e-08, 3.6852617668760624e-07, 3.34178239216774e-08, 3.100802616057133e-07, 3.112135111110933e-08]
(18_w,36)-aCMA-ES (mu_w=10.2,w_1=18%) in dimension 6 (seed=172350, Mon Oct 14 17:30:53 2019)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1   3656 -1.369110915553734e+00 1.0e+00 3.23e-01  3e-01  3e-01 0:00.0
    2   3692 -1.822354980160982e+00 1.4e+00 3.83e-01  3e-01  4e-01 0:00.0
    3   3728 -2.411128420139160e+00 1.8e+00 4.62e-01  4e-01  5e-01 0:00.0
  100   7220 -3.322368011409087e+00 2.7e+00 3.78e-04  2e-07  5e-07 0:00.6
  114   7724 -3.322368011415500e+00 2.3e+00 1.02e-04  2e-08  4e-08 0:00.7
termination on tolfun=1e-11 after 2 restarts (Mon Oct 14 17:30:54 2019)
final/bestever f-value = -3.322368e+00 -3.322368e+00
incumbent solution: [0.20168950330094115, 0.1500106848870168, 0.47687397362863004, 0.2753324337897443, 0.3116516140392232, 0.657300537103042]
std deviation: [3.218294195595563e-08, 3.759597541519509e-08, 4.087490004537714e-08, 2.4501803176587784e-08, 1.781144440390789e-08, 2.7195417110053648e-08]
(36_w,72)-aCMA-ES (mu_w=19.7,w_1=10%) in dimension 6 (seed=172351, Mon Oct 14 17:30:54 2019)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1   7797 -2.304277146858279e+00 1.0e+00 3.26e-01  3e-01  3e-01 0:00.0
    2   7869 -2.734325079306702e+00 1.6e+00 3.97e-01  3e-01  4e-01 0:00.0
    3   7941 -1.902834791183585e+00 2.0e+00 4.75e-01  4e-01  5e-01 0:00.0
   79  13413 -3.322368011415422e+00 2.5e+00 3.82e-03  4e-08  8e-08 0:00.9
termination on tolfun=1e-11 after 3 restarts (Mon Oct 14 17:30:55 2019)
final/bestever f-value = -3.322368e+00 -3.322368e+00
incumbent solution: [0.20168950832441573, 0.1500107222472497, 0.47687396977192514, 0.27533243390673473, 0.3116516077098976, 0.657300524691937]
std deviation: [7.961726379108091e-08, 6.9418454708484e-08, 7.507385330519629e-08, 4.652430539211889e-08, 3.61561333662909e-08, 4.718593079228665e-08]
```

**Comment by a-z-e-r-i-l-a** [comment]
@nikohansen 

Yest your code also worked for me, but in your code the bounds are not defined for every dimensions, right? For example what if instead of [0,1] for one of the dimensions, I want to search between [0.5, 1]

I see the following as the general use of the code:

```

import hpolib.benchmarks.synthetic functions as _hpolib_fcts
import cma

class Hartmann6:
    """see http://www.sfu.ca/~ssurjano/hart6.html"""
    def __init__(self):
        self.f = _hpolib_fcts.hartmann6.Hartmann6()
        self.bounds  = np.array([[0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1]])
    def __call__(self, x):
      return self.f.objective_function(x)['function_value']
HM = Hartmann6()
xopt, es = cma.fmin2(HM, 6 * [0.5], 0.3, {'bounds': HM.bounds ,  'verbose':-9}, restarts=3)

```

which gives an error form me:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-60-b9dd69b9d442> in <module>
>       7       return self.f.objective_function(x)['function_value']
>       8 HM = Hartmann6()
> ----> 9 xopt, es = cma.fmin2(HM, 6 * [0.5], 0.3, {'bounds': HM.bounds ,  'verbose':-9}, restarts=3)
> 
> ~/.local/share/virtualenvs/tf-tRAPLeXL/lib/python3.6/site-packages/cma/evolution_strategy.py in fmin2(*args, **kwargs)
>    3750 
>    3751     """
> -> 3752     res = fmin(*args, **kwargs)
>    3753     return res[0], res[-2]
>    3754 
> 
> ~/.local/share/virtualenvs/tf-tRAPLeXL/lib/python3.6/site-packages/cma/evolution_strategy.py in fmin(objective_function, x0, sigma0, options, args, gradf, restarts, restart_from_best, incpopsize, eval_initial_x, parallel_objective, noise_handler, noise_change_sigma_exponent, noise_kappa_exponent, bipop, callback)
>    4084                     es = CMAEvolutionStrategy(best.x, sigma_factor * sigma0, opts)
>    4085                 else:
> -> 4086                     es = CMAEvolutionStrategy(x0, sigma_factor * sigma0, opts)
>    4087                 # return opts, es
>    4088                 if callable(objective_function) and (
> 
> ~/.local/share/virtualenvs/tf-tRAPLeXL/lib/python3.6/site-packages/cma/evolution_strategy.py in __init__(self, x0, sigma0, inopts)
>    1394         self.boundary_handler = opts['BoundaryHandler']
>    1395         if isinstance(self.boundary_handler, type):
> -> 1396             self.boundary_handler = self.boundary_handler(opts['bounds'])
>    1397         elif opts['bounds'] not in (None, False, [], [None, None]):
>    1398             utils.print_warning("""
> 
> ~/.local/share/virtualenvs/tf-tRAPLeXL/lib/python3.6/site-packages/cma/constraints_handler.py in __init__(self, bounds)
>     226         """
>     227         # BoundaryHandlerBase.__init__(self, bounds)
> --> 228         super(BoundTransform, self).__init__(bounds)
>     229         self.bounds_tf = BoxConstraintsLinQuadTransformation(self.to_dim_times_two(bounds))
>     230 
> 
> ~/.local/share/virtualenvs/tf-tRAPLeXL/lib/python3.6/site-packages/cma/constraints_handler.py in __init__(self, bounds)
>      22 
>      23         """
> ---> 24         if bounds in [None, (), []]:
>      25             self.bounds = None
>      26         else:
> 
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by nikohansen** [comment]
> but in your code the bounds are not defined for every dimensions, right?

In the posted experiment, the bounds are defined for each and every variable between [0, 1].

> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Apparently, `numpy` arrays don't work for defining bounds. I recommend to check out the documentation of the code and/or `cma.CMAOptions('bound')`, I am sure there are also examples. Sorry, I don't have currently the time to dig and check the right syntax.

BTW, using `'verbose':-9` is not the best of all ideas in a first attempt. Verbosity is there for a reason. Like this you might have suppressed a useful warning giving the solution at hand.

**Comment by a-z-e-r-i-l-a** [comment]
> Apparently, `numpy` arrays don't work for defining bounds. I recommend to check out the documentation of the code and/or `cma.CMAOptions('bound')`, I am sure there are also examples. Sorry, I don't have currently the time to dig and check the right syntax.

The examples also use the bounds the way I used them. I have tried both np.arrays and lists or tuples for bounds all result in the same error.

**Comment by nikohansen** [comment]
> The examples also use the bounds the way I used them.

Really? Which examples?

How about following
```
'bounds': '[None, None]  # lower (=bounds[0]) and upper domain boundaries, each a scalar or a list/vector'
```

**Comment by a-z-e-r-i-l-a** [comment]
Sorry I had seen the example from the GpyOpt algorithm, and not that I checked again, this seems to be the right way to define the bounds:

import hpolib.benchmarks.synthetic_functions as _hpolib_fcts
import cma

```
class Hartmann6:
    """see http://www.sfu.ca/~ssurjano/hart6.html"""
    def __init__(self):
        self.f = _hpolib_fcts.hartmann6.Hartmann6()
        bounds  = np.array([[0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1]])
        lB = np.asarray(bounds)[:,0]
        uB = np.asarray(bounds)[:,1]
        self.bounds  = [lB, uB]
    def __call__(self, x):
        return self.f.objective_function(x)['function_value']
HM = Hartmann6()
xopt, es = cma.fmin2(HM, 6 * [0.5], 0.3, {'bounds':self.bounds,  'verbose':-9}, restarts=3)
```
In some different examples other than Hartmann the earlier mentioned way to give the bounds had also worked for me so I thoutght that should be the general right way, but it seems the most general working way is like above.
