### ISSUE TITLE
'tolfun' termination criteria not correct

### ISSUE THREAD

**Issue by hogloid** [CMA-ES/pycma#98]
Under boundary constraints,
cmaes.fit.fit is ordered by function value + boundary penalty (cf: https://github.com/CMA-ES/pycma/blob/master/cma/evolution_strategy.py#L2533)

On the other hand, 'tolfun' terminates CMA-ES iff the function value differs at most opts['tolfun'], but the formula is just taking the first and last element of cmaes.fit.fit. (cf: https://github.com/CMA-ES/pycma/blob/master/cma/evolution_strategy.py#L3422)
This is not necessarily minimum/maximum of the population because of boundary penalty.

This can lead to wrong termination.
Especially, on the 1st epoch, if the function values are only slightly different, es.fit.fit[-1] - es.fit.fit[0] can be even negative and terminates immediately.

**Comment by nikohansen** [comment]
Fixed in commit 6232b0b.
